WebAssembly/spec

Contributing.md, README.md, ml-proto/README.md
And some basic top-level text, and a few trivial corrections.
=> Add an introductory message in the top-level README.md

README.md, ml-proto/test/ackermann.wasm
Signed-off-by: Valentin Ilie <valentin.ilie@intel.com>
=> test: Add Ackermann function

ml-proto/src/lexer.mll, ml-proto/src/parser.mly, ml-proto/src/script.ml, ml-proto/src/script.mli, ml-proto/test/basic.wasm
To write unit tests, it'd be useful to be able to assert an expected return value, otherwise all we're testing is that an error isn't hit.
The SExpr syntax is `(asserteq (invoke export-index args-to-call) expected-results)`.  The reason for the nested `invoke` is to clearly separate invoke args from expected results and to allow us to asserteq other forms later.  An alternative would have been to just have an `assert` that evaluates a boolean condition, but that would require injecting `Invoke` into general expressions or using an `Ast.Call` expression which violate the point of exports (all execution in a module originates with exports; `Eval.eval` sorta violates this already, but I was thinking of changing it to mock up a new module instead of reusing the current module).
=> Add command (asserteq (invoke ...) expected)

ml-proto/README.md, ml-proto/src/eval.ml, ml-proto/src/eval.mli, ml-proto/src/lexer.mll, ml-proto/src/parser.mly, ml-proto/src/script.ml, ml-proto/src/script.mli, ml-proto/test/basic.wasm
Currently `Eval.eval` evaluates expressions inside the current wasm module (kinda like a JS direct eval) which feels like it violates module encapsulation invariants.  This patch mocks up a dummy module.
=> Don't Eval.eval in existing module

ml-proto/src/parser.mly
Manifests when running test suite with multiple file arguments.
=> Fix mutability bug

ml-proto/src/ast.ml, ml-proto/src/check.ml, ml-proto/src/eval.ml, ml-proto/src/lexer.mll, ml-proto/src/memory.ml, ml-proto/src/memory.mli, ml-proto/src/parser.mly, ml-proto/src/types.ml, ml-proto/test/memory.wasm
It's my understanding that we want to be able to have multiple data segments and to control the offset in linear memory into which each segment is loaded.  For simplicity of validation and because I don't see the need for this flexibility, the validation rules require the segments to be disjoint and ordered by offset.
For good form, I should also add negative validation tests (breaking the rules).  Rather than giving each one a separate file and pattern-matching on the exact text output, I think this is another good usecase for a new script command that you give a module that should fail to validate and then perhaps a string key to identify which error you're expecting.  Need some agreement on #14 before pursuing that.
=> Allow multiple data segments

ml-proto/README.md, ml-proto/runtests.py, ml-proto/src/Makefile, ml-proto/src/check.ml, ml-proto/src/lexer.mll, ml-proto/src/parser.mly, ml-proto/src/script.ml, ml-proto/src/script.mli, ml-proto/test/basic.wasm, ml-proto/test/exports.wasm, ml-proto/test/memory.wasm, ml-proto/travis/build-test.sh
Two patches (on top of #14):
The first patch adds an `(invalid (module ...) "error")` command that checks that the given module fails in the checker (as opposed to during parsing which is outside the spec) with the given `"error"`.  This command is then used to test the corner cases of the `memory` section.
The second patch added tests for the corner cases of exports and caught a minor "bug"&mdash;the AST is allowed to export a single name twice&mdash;which is fixed.
=> Add invalid command

ml-proto/src/arithmetic.ml, ml-proto/src/ast.ml, ml-proto/src/lexer.mll, ml-proto/src/parser.mly, ml-proto/src/values.ml, ml-proto/test/float32.wasm
@lukewagner, @kg, doing it asm.js-style.
=> Implement accurate float32 semantics

ml-proto/README.md, ml-proto/src/ast.ml, ml-proto/src/check.ml, ml-proto/src/eval.ml, ml-proto/src/lexer.mll, ml-proto/src/memory.ml, ml-proto/src/parser.mly, ml-proto/test/forward.wasm, ml-proto/test/memory.wasm
This patch moves the linear memory operations a bit closer to the [design doc](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#linear-memory-operations).  It doesn't attempt to fix the type naming situation (#26) but it does:
* remove the near/far distinction since >4GiB heaps are [future feature](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#linear-memory-bigger-than-4gib).  The SExpr opcode names are future-compatible under the assumption that we bias toward near ops ("" means near, "far" means far);
* rename `get*` to `load` and `set*` to `store`.
=> Remove near|far split and rename (Get|Set)Memory

ml-proto/README.md, ml-proto/src/ast.ml, ml-proto/src/check.ml, ml-proto/src/eval.ml, ml-proto/src/lexer.mll, ml-proto/src/lib.ml, ml-proto/src/lib.mli, ml-proto/src/memory.ml, ml-proto/src/memory.mli, ml-proto/test/memory.wasm
Extending #30, this patch moves the alignment aspect of linear memory ops to what's in the [design repo](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#alignment) as follows:
* remove `Memory.alignment` from `Memory` since alignment makes no semantic difference
* add `Ast.alignment`, since load/store AST nodes do have an alignment field
* switches `alignment` from a binary `Aligned|Unaligned` to an `int` which is validated to be {1,2,4,8} and smaller than the element size
=> Refine alignment

ml-proto/src/arithmetic.ml, ml-proto/src/ast.ml, ml-proto/src/lexer.mll, ml-proto/test/multivalue.wasm, ml-proto/test/unsigned.wasm
The signed remainder operator in particular is not clearly described as
a modulus function, because it returns negative values when the dividend
is negative. This patch renames it from "mod" to "rem", which is also in
accordance with AstSemantics.md.
=> Rename Mod to Rem.

ml-proto/src/arithmetic.ml, ml-proto/src/ast.ml, ml-proto/src/lexer.mll
This is what the design repo calls it. And in particular, it's useful to
avoid calling it "round" because it's semantically different from both
JS's Math.round and C's round.
=> Rename round to nearestint.

ml-proto/src/arithmetic.ml, ml-proto/src/ast.ml, ml-proto/src/lexer.mll
This adds floating point min and max, from AstSemantics.md. They don't have semantics yet; I'm working on that in the [float-bits](https://github.com/WebAssembly/spec/tree/float-bits) branch.
=> Add min and max operators.

ml-proto/README.md, ml-proto/src/host/lexer.mll, ml-proto/src/host/parser.mly, ml-proto/src/spec/ast.ml, ml-proto/src/spec/check.ml, ml-proto/src/spec/eval.ml, ml-proto/src/spec/memory.ml, ml-proto/src/spec/memory.mli, ml-proto/test/memory.wasm
This patch updates ml-proto to match the changes in #341.  The only remaining difference is that, for all opcode names, not just load/store, ml-proto uses the "i32" form vs. "int32".  (I could see this difference resolved in either spec or design, so I'll leave that for a separate issue.)
=> Update load/store to match design changes

ml-proto/runtests.py
With this change you can get full stack traces out of main.native by doing ```export OCAMLRUNPARAM=b```.
So:
```
/usr/local/google/home/kgadd/Projects/wasm-spec/ml-proto/src/_build/host/main.native: uncaught exception Failure("span")
Raised at file "pervasives.ml", line 31, characters 25-45
```
becomes
```
/usr/local/google/home/kgadd/Projects/wasm-spec/ml-proto/src/_build/host/main.native: uncaught exception Failure("span")
Raised at file "given/source.ml", line 24, characters 16-32
Called from file "spec/check.ml", line 222, characters 35-50
Called from file "spec/check.ml", line 157, characters 4-24
Called from file "spec/check.ml", line 204, characters 4-28
Called from file "list.ml", line 110, characters 24-31
Called from file "spec/check.ml", line 221, characters 6-38
Called from …
```
=> Update runtests to compile with debugging information

ml-proto/src/host/main.ml
input returns 0 when it reaches the end of the file; other values may
indicate merely a short read. This fixes #72.
=> Fix a bug in the detection of end-of-file.

ml-proto/README.md, ml-proto/src/host/lexer.mll, ml-proto/src/host/parser.mly, ml-proto/src/host/print.ml, ml-proto/src/host/script.ml, ml-proto/src/host/script.mli, ml-proto/test/memory_fault.wasm
This patch adds a command `(assert_fault (invoke "foo" ...args) "...fail regex")` that asserts a specified runtime failure.
=> Add assert_fault script command

ml-proto/src/spec/arithmetic.ml, ml-proto/test/int32.wasm
A short, illustrative implementation of integer bit operations, unoptimized since I assume the spec isn't prescribing particular optimizations. Test cases can benefit from hex integer literals though.
=> implementation and tests for clz, ctz, and popcnt

ml-proto/README.md, ml-proto/src/Makefile, ml-proto/src/host/lexer.mll, ml-proto/src/host/params.ml, ml-proto/src/host/parser.mly, ml-proto/src/host/script.ml, ml-proto/src/spec/ast.ml, ml-proto/src/spec/check.ml, ml-proto/src/spec/eval.ml, ml-proto/src/spec/eval.mli, ml-proto/src/spec/memory.ml, ml-proto/src/spec/memory.mli, ml-proto/test/resizing.wasm
This patch adds resizing as described in [design/AstSemantics.md#linear-memory](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#linear-memory).
=> Add resizing

ml-proto/src/host/lexer.mll, ml-proto/src/host/parser.mly, ml-proto/src/host/print.ml, ml-proto/src/spec/ast.ml, ml-proto/src/spec/check.ml, ml-proto/src/spec/eval.ml, ml-proto/test/forward.wasm
Globals were moved out of the MVP in [design/#344](https://github.com/WebAssembly/design/pull/344); this patch updates the ML spec accordingly.
=> Remove globals

ml-proto/src/given/float32.ml, ml-proto/src/given/float64.ml
This fixes a thinko in the min and max functions. Tests for this will be added soon; they're in development on the [float-tests](https://github.com/WebAssembly/spec/tree/float-tests) branch.
=> Fix the min and max computation for the case where the operands are equal

ml-proto/src/given/float32.ml, ml-proto/src/given/float64.ml
mod_float is not always correctly rounded on all platforms. This patch uses a safer algorithm to check whether a number is even.
=> Avoid relying on correct rounding of mod_float.

ml-proto/src/.gitignore, ml-proto/src/Makefile, ml-proto/src/_tags
.gitignore is simplified since now almost all build files reside in _build.
Using "git archive" to build a zip file in target "zip".
=> Now using ocamlbuild for building. Rewrote Makefile, introduces _tags.

ml-proto/src/spec/memory.ml
As requested by @sunfishcode [here](https://github.com/WebAssembly/spec/pull/84#discussion_r40200166)
=> Replaced explicit truncation on memory store with implicit truncation+comment

ml-proto/Makefile
Apparently ocamlbuild decides whether or not to include debug symbols sufficient to perform a backtrace based on the output executable file name. This commit changes the name used, so that we can get backtraces.
=> Use the arcane ocamlbuild incantation that actually gets debug symbols.

ml-proto/host/parser.mly, ml-proto/host/print.mli, ml-proto/host/script.ml, ml-proto/host/script.mli, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/check.mli, ml-proto/spec/eval.ml, ml-proto/spec/eval.mli
I suppose this is personal familiarity, but 'modul' initially made me wonder if it's some strange OCaml keyword that I hadn't previously encountered.
=> Rename 'modul' to 'module_'.

ml-proto/README.md, ml-proto/spec/ast.ml
The README.md copy keeps going out of date with asm.ml. The ML source
code ought to be readable as documentation, since it also serves as a
specification, so if there is a readability issue with ast.ml, we
should fix it.
=> Replace the AST definition in README.md with a link to ast.ml.

ml-proto/host/lexer.mll, ml-proto/host/parser.mly, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/memory.ml, ml-proto/spec/memory.mli
@sunfishcode pointed out that we consistently use "wrap" instead of "truncate" to describe larger-to-smaller integer conversions, so this PR renames `StoreTrunc` to `StoreWrap` which is nicer anyway since it's shorter and replaces an abbreviation with a real word.  Also tidies up README.md.
=> Rename StoreTrunc to StoreWrap for consistency

ml-proto/runtests.py, ml-proto/travis/build-test.sh
This fixes #59. I have no idea if it works on Windows. If this fix is inappropriate, please tell me what I can do to fix this instead. Thanks!
=> Fix the path to the wasm executable to match what the Makefile builds.

ml-proto/Makefile
- Only build opt version by default.
- Mark `main.native` and `main.d.byte` as intermediate targets.
- Introduce test target to invoke test runner.
This should address issue #102 .
=> Makefile improvements

ml-proto/host/script.ml, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/eval.mli, ml-proto/test/memory.wast
This PR makes it a validation error to use linear memory operations (load, store, page_size, resize_memory, memory_size) when there is no memory section declared in the module.  Since it is possible to have a `(memory 0)` section (which allows memory ops but doesn't require allocation), there is no loss of expressiveness for producers.  Rather, this is a simple a priori way to capture the wasm producer's intent to never use linear memory that allows the impl to take advantage of this (to reduce footprint, avoid corner cases in codegen) without having to worry about a linear memory later appearing (via resize_memory or dynamic linking).  This restriction could later be backwards-compatibly relaxed if necessary.  The main expected use is apps using …
=> Only validate memops when there is a memory section

ml-proto/given/lib.ml, ml-proto/given/lib.mli, ml-proto/host/params.ml, ml-proto/host/parser.mly, ml-proto/host/script.ml, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/eval.mli, ml-proto/spec/memory.ml, ml-proto/spec/memory.mli, ml-proto/test/memory.wast
This PR is intended to address some of the issues raised in #80 by using `int64` throughout `spec`/.  The BigArray `int` limitation is, as suggested in #80, addressed by modeling creation of an array bigger than `max_int` as an `Out_of_memory` trap.
=> Use int64 for addresses and sizes, isolate BigArray int limitation

ml-proto/Makefile
...plus a couple of minor clean-ups.
=> Fix Makefile to detect changes again

ml-proto/spec/ast.ml
This follows up on a comment in #96 by adding comments for the remaining AST nodes. I also updated a few other nearby AST node comments.
=> Comment LoadExtend and StoreTrunc and update comments for other nodes.

ml-proto/TestingTodo.md, ml-proto/test/endianness.wast
This tests, if all load and store operations use little-endian.
=> Endianness test

ml-proto/host/lexer.mll, ml-proto/host/parser.mly
=> Use underscores in token names

ml-proto/README.md, ml-proto/host/lexer.mll, ml-proto/host/parser.mly, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/memory.ml, ml-proto/spec/memory.mli, ml-proto/test/address.wast, ml-proto/test/memory.wast
This PR adds the immediate offset described in [AstSemantics.md#addressing](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#addressing).  I'd rather not block on the broader question of opcode naming in [design/#374](https://github.com/WebAssembly/design/pull/374), so this PR just does what seems like the obvious extension to the current scheme of putting load/store immediates in the opcode name (prefixed with `+` for the offset).
=> Add constant offsets to spec

ml-proto/TestingTodo.md, ml-proto/test/left-to-right.wast
This tests if store instructions and calls evaluate their operands from left to right, too.
=> Second left-to-right test

ml-proto/host/lexer.mll, ml-proto/host/params.ml, ml-proto/host/parser.mly, ml-proto/host/script.ml, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/eval.mli, ml-proto/spec/sugar.ml, ml-proto/test/has_feature.wast
This implements `has_feature` as described in [the design](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#feature-test).
=> Implement has_feature.

ml-proto/TestingTodo.md, ml-proto/test/float_exprs.wast, ml-proto/test/resizing.wast
This combines two little tests:
The first one tests that page_size is a power of two.
The second one converts both integer types to the corresponding floating point types (and back again) and tests that those conversions aren't folded away.
=> Tests for correct page size and float conversion

ml-proto/host/lexer.mll
=> Disallow control characters in literals

ml-proto/README.md, ml-proto/travis/install-ocaml.sh
Adding a sha256 checksum of the tarball.
=> Moving to a mirror of ocaml with https.

ml-proto/test/float_exprs.wast, ml-proto/test/names.wast
Inspired by https://github.com/WebAssembly/design/issues/415 here is a PR that fixes the test name in question, and adds a new test for symbol name handling.
This tests a bunch of interesting names, but one thing it doesn't test is for newline characters embedded in names. That doesn't presently appear to with in the spec interpreter; I'll file a separate bug.
=> Fix a copy+paste error in a test name, and add a new test for symbol names

ml-proto/spec/check.ml, ml-proto/test/address.wast
They should be a uint32 value.
This fixes #161.
=> Do not accept a too-large offset in memory accesses

AUTHORS, LICENSE
The AUTHORS file claims to be a list of people and their organizations who have contributed to the repository, but it isn't complete in that it doesn't list many of the people who have contributed, and it doesn't list the organizations of the people it does list. 
And, the LICENSE file was modified from the original Apache text in an apparent attempt to connect it with the AUTHORS file, however the change was made in the appendix section, which only contains suggested boilerplate text for use with the license, and we aren't currently using the boilerplate.
This PR proposes to rectify these issues by reverting the LICENSE to the original text and removing the AUTHORS file for now. If there is a future need for an AUTHORS file, we can start a new one, in a deliberate way.
=> Remove the AUTHORS file and revert to a standard LICENSE.

ml-proto/spec/check.ml, ml-proto/test/labels.wast, ml-proto/test/switch.wast
Disallows redundant arguments to a break targeting a label of type `None` (addresses #179).
Conceptually, there is no specific harm in allowing this, but it also is not useful. Rather be consistent with the checking for calls.
=> Tighter typing of Break

ml-proto/test/labels.wast
All loops in the test suite have a trailing `br`, so we didn't have a test yet for loops not automatically looping. I noticed this on binaryen which had this wrong.
=> Add a test for a loop without a trailing br

ml-proto/host/builtins.ml, ml-proto/test/address.wast, ml-proto/test/func_ptrs.wast, ml-proto/test/imports.wast, ml-proto/test/store_retval.wast
'stdio' is confusing because it's a set of functions with the main purpose being to support spec conformance tests, so this PR proposes naming it 'spectest'.
=> Rename the 'stdio' module to 'spectest'.

ml-proto/test/labels.wast
The loop1 method is too simple for LLVM, which then makes it return just 5.
Though this proves that the code is correct, we probably want to have the
code generation all the same.
This patch makes a loop3 method based on loop1 so that the code ais  bit
different but at least the compiler can no longer optimize it all away.
We've left loop1 to show the difference in compiler technologies
=> Creating an obfuscated Loop1

ml-proto/host/lexer.mll, ml-proto/test/float_literals.wast
See https://github.com/WebAssembly/sexpr-wasm-prototype/issues/29
=> Allow trailing dot before exponent in float literal

ml-proto/test/i32.wast, ml-proto/test/i64.wast
The leading brace would confuse generic s-exp parsers.
=> Avoid (; for comments, use ;;

ml-proto/host/lexer.mll, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/kernel.ml
I realized that since `0` is already an invalid alignment (currently fails the "is a power of 2" check) we don't need alignment to be an `int option`, we can simply use an `int`; no reason to have two sentinel cases.  This also makes it an epsilon simpler when talking about binary encoding.
=> Use 0 instead of None for alignment

ml-proto/host/parser.mly, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/desugar.ml, ml-proto/spec/eval.ml, ml-proto/spec/kernel.ml, ml-proto/test/fac.wast, ml-proto/test/labels.wast
This implements the second half of https://github.com/WebAssembly/design/pull/489.
Desugaring br_if to if+break was fairly awkward; adding br_if to the kernel
language was straightforward and avoided the awkwardness.
This change happened to expose an aspect of `br_if`'s type checking which
differed from my expectations, so I've taken the liberty of fixing that
too. See the deleted assert_invalid in test/labels.wast and the added
$br_if1 testcase. `br_if` either sends its value to the destination label
or to its own result.
=> Put br_if conditions last.

ml-proto/host/lexer.mll, ml-proto/host/parser.mly, ml-proto/host/print.ml, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/desugar.ml, ml-proto/spec/eval.ml, ml-proto/spec/kernel.ml, ml-proto/test/start.wast
The following is the list of what I have done to add start functionality
- I have changed the Ast module and Kernel module to include the start function index.
- Have the start function run as soon as the module is loaded.
- In the print_module function in host/print.ml, I have added the start function to be the output to the screen
- Add test/start.wast to test the start function
Please consider if we should add this feature to the main repo
=>  Support start, add testcase, and can be executed properly

ml-proto/test/conversions.wast
The test in 203a50b92478714bace87e8166b081cd7e1aed11 prompted me to notice a few more interesting cases for `f32.demote_f64`.
=> Test a few more f32.demote_f64 edge cases.

ml-proto/test/func_ptrs.wast
Also add in an import to help detect issues with the v8 encoding
which uses a different index space that includes imports and functions.
=> Test that function indexes work in the function tables.

ml-proto/test/labels.wast
To resolve https://github.com/WebAssembly/spec/issues/210
=> Add a test of block label redefinition.

ml-proto/README.md, ml-proto/host/lexer.mll, ml-proto/host/parser.mly, ml-proto/spec/ast.ml, ml-proto/spec/desugar.ml, ml-proto/test/fac.wast, ml-proto/test/forward.wast, ml-proto/test/labels.wast, ml-proto/test/memory.wast, ml-proto/test/unreachable.wast
The post-order binary format induces minor changes to `if`:
- There is only one opcode for `if`, with and without else-branch.
- The branches can have sequences of expressions (they are effectively blocks).
This PR reflects these generalisations in the AST and the S-expression format. Unfortunately, this required tagging the branch blocks in the S-expression syntax, so that the both lists can be distinguished. The tags can be omitted if the sequence consists of exactly one expression, thereby keeping the previous concrete syntax valid. See README for details.
=> Adjust `if` to match post-order format.

ml-proto/TestingTodo.md, ml-proto/spec/check.ml, ml-proto/spec/eval.ml, ml-proto/spec/memory.ml, ml-proto/test/address.wast, ml-proto/test/endianness.wast, ml-proto/test/float_memory.wast, ml-proto/test/left-to-right.wast, ml-proto/test/memory.wast, ml-proto/test/memory_redundancy.wast, ml-proto/test/memory_trap.wast, ml-proto/test/start.wast, ml-proto/test/store_retval.wast, ml-proto/test/traps.wast
Otherwise the tests will not be consistent when run on an implementation that rounds up the memory sizes in bytes to the page size units, and impossible for the runtime to check given that the binary encoding does not store the memory sizes in bytes.
=> Use page aligned memory sizes in the tests.

ml-proto/spec/eval.ml, ml-proto/test/memory_trap.wast, ml-proto/test/resizing.wast
To go along with WebAssembly/design#598
=> grow_memory takes page size

ml-proto/spec/check.ml, ml-proto/test/break-drop.wast, ml-proto/test/functions.wast, ml-proto/test/labels.wast
This reverses #180, and adds a number of corresponding tests.
Motivation: not allowing optional operands to be implicitly dropped (1) reduced the compositionality of the language, (2) made it harder to allow multiple targets (like with a br_if also returning its operand), and (3) put an extra burden on bottom-up type checkers, where the arity might not be known upfront. And with multiple value, we eventually would want to lift this restriction again anyway.
This should address issues #227, and enable WebAssembly/design#539.
@jcbeyler, you filed #179, which lead to #180. Are you okay with reverting to status ante quo?
=> Allow subtyping on optional operands

ml-proto/TestingTodo.md, ml-proto/test/left-to-right.wast
This tests if br_if and br_table arguments are evaluated left-to-right.
Until #227 is solved, a small hack circumvents any "arity mismatch" error
messages.
=> Add br_if and br_table to left-to-right.wast

ml-proto/README.md, ml-proto/given/lib.ml, ml-proto/given/lib.mli, ml-proto/given/source.ml, ml-proto/host/encode.ml, ml-proto/host/encode.mli, ml-proto/host/lexer.mll, ml-proto/host/main.ml, ml-proto/host/parse.ml, ml-proto/host/parse.mli, ml-proto/host/parser.mly, ml-proto/host/print.ml, ml-proto/host/run.ml, ml-proto/host/run.mli, ml-proto/host/script.ml, ml-proto/host/script.mli, ml-proto/runtests.py, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/decode.ml, ml-proto/spec/decode.mli, ml-proto/spec/desugar.ml, ml-proto/spec/eval.ml, ml-proto/spec/eval.mli, ml-proto/spec/kernel.ml, ml-proto/test/block_comments.wast, ml-proto/test/memory.wast
Add working (post-order) encoder & decoder. Supersedes PR #261.
Extends the test runner with encoding & decoding of all test files via a wast->wasm transcoding and loading the resulting modules. Works for all current tests.
There are still a number of smaller TODOs left, but I think it makes more sense to address them in follow-ups. Other follow-up work: wasm->wast reverse transcoding, more aggressive tests and testing capabilities.
We'll probably also need to revise the use of different integer types throughout the spec, which is not always consistent with what the binary format supports.
=> Binary encoder & decoder

ml-proto/TestingTodo.md, ml-proto/test/conversions.wast, ml-proto/test/f32.wast, ml-proto/test/f32_cmp.wast, ml-proto/test/f64.wast, ml-proto/test/f64_cmp.wast, ml-proto/test/float_exprs.wast, ml-proto/test/float_literals.wast, ml-proto/test/float_memory.wast, ml-proto/test/float_misc.wast, ml-proto/test/int_exprs.wast, ml-proto/test/nan-propagation.wast
This adds more floating point rounding tests, more expression optimizer
bait tests, more real-world floating point bug tests, and more comments.
=> More tests!

ml-proto/README.md, ml-proto/given/lib.ml, ml-proto/given/lib.mli, ml-proto/host/format.ml, ml-proto/host/parse.ml, ml-proto/host/parse.mli, ml-proto/host/parser.mly, ml-proto/host/run.ml, ml-proto/host/script.ml, ml-proto/host/script.mli, ml-proto/spec/decode.mli, ml-proto/test/binary.wast
This PR adds support for defining modules directly in terms of a binary string in the text format:
```
(module "\00asm\0b\00\00\00")
(assert_invalid (module "\00as") "unexpected end")
```
To ease formatting, strings can be split up into several literals, which are simply concatenated:
```
(module
"\00asm"  ;; magic header
"\0b\00\00\00"  ;; version
)
```
The same string splitting is now allowed in `segment` nodes.
Further changes:
- Correct string escaping in S-expr output.
- Tweaked S-expr output to match binary section order.
- Type and function definitions are named with their index, for easier reference.
- Functions are now formatted literally using the `(type i)` syntax for their signature, in order to not implicitly change the content of the type section. (One step closer to (parse …
=> Allow binary modules in text format

README.md
I've received some questions about the status of the spec and the plans going forward. This PR briefly documents ideas that have been around, but not yet written down anywhere.
=> Spell out the expected plans for a WebAssembly spec.

ml-proto/test/float_exprs.wast, ml-proto/test/float_misc.wast, ml-proto/test/int_exprs.wast, ml-proto/test/memory.wast
A few more floating point tests, but also includes a test for memory size overflow.
=> Misc tests

ml-proto/runtests.py, ml-proto/test/expected-output/if_label_scope.fail.wast.log, ml-proto/test/if_label_scope.fail.wast, ml-proto/test/labels.wast
Hi! I'd like to add test cases we ran into in our implementation and which could be useful for others:
- a test for if/then/else where the depths are not labels, but raw integer indices.
- a test for if/then/else where the label target of a `br` in the `else` is the label of the `then` block.
Unfortunately, the second test (at the end of the file) doesn't work: the parser complains that the label `$l` is unknown, which is exactly what we are testing here. The correct behavior would be to silently swallow the error and consider the test as passed. Am I missing something here?
=> Add tests for if/then/else with indices + unknown label;

ml-proto/host/format.ml, ml-proto/runtests.py, ml-proto/test/block.wast, ml-proto/test/br.wast, ml-proto/test/loop.wast, ml-proto/test/return.wast, ml-proto/test/unreachable.wast
This time:
- loop
- br
- return
- bunch of additions to previous tests
Plus a bug fix in the pretty printer.
=> Next batch of tests

ml-proto/test/br.wast, ml-proto/test/br_if.wast, ml-proto/test/br_table.wast, ml-proto/test/typecheck.wast
This is a PR against the void branch, which adds a few more tests.
Specifically, this tests constructs which merge values from two control paths, to ensure that the types match even when the resulting value is dropped.
=> Add tests for conflicting-but-ultimately-dropped values.

ml-proto/host/encode.ml, ml-proto/host/encode.mli, ml-proto/spec/decode.ml, ml-proto/test/binary.wast
To sync with more recent changes in BinaryFormat.md. Also bumps version to 0xc.
Fixes #299.
=> Updates for binary format

ml-proto/test/call_indirect.wast, ml-proto/test/func.wast
- Extend call_indirect test to check that signature is nominal.
- Avoid use of implicit signatures in call_indirect.wast tests.
- Add tests to func.wast to verify correct implicit signature desugaring.
=> Refine and extend tests for function signatures

ml-proto/host/arrange.ml, ml-proto/host/encode.ml, ml-proto/host/lexer.mll, ml-proto/host/parser.mly, ml-proto/spec/ast.ml, ml-proto/spec/check.ml, ml-proto/spec/decode.ml, ml-proto/spec/desugar.ml, ml-proto/spec/eval.ml, ml-proto/spec/kernel.ml, ml-proto/test/globals.wast
Implements global declarations as of WebAssembly/design#682. Still missing: mutability, import/export.
Also, binary opcodes currently don't match WebAssembly/design#727, due to conflicts with WebAssembly/design#711.
=> Implement globals

ml-proto/spec/check.ml, ml-proto/spec/types.ml, ml-proto/test/memory.wast
=> Check maximum alignment

ml-proto/spec/check.ml, ml-proto/spec/memory.ml, ml-proto/spec/memory.mli, ml-proto/test/memory.wast
Use the stored size as the natural alignment for memory operations, rather than the size of the value (4 or 8 bytes).
The design repo [says](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#alignment):
> An alignment value which is the same as the memory attribute size is considered to be a natural alignment.
I would interpret "memory attribute size" to be the size of the value stored in memory, rather than the size of the value, which is the current state of the spec.
=> Use the stored size as the natural alignment for memory operations

ml-proto/spec/check.ml, ml-proto/spec/memory.ml, ml-proto/spec/memory.mli, ml-proto/test/memory.wast
Use the stored size as the natural alignment for memory operations, rather than the size of the value (4 or 8 bytes).
=> Merge natural alignment change to binary-0xc

ml-proto/README.md, ml-proto/host/encode.ml, ml-proto/runtests.py, ml-proto/spec/decode.ml, ml-proto/winmake.bat
The binary encoding of a Function Body should start with the size of the AST, followed by declaring the locals. Instead we were declaring the locals first.
Also made a minor change to the README because `ocamlbuild` is no longer shipped with `ocaml` in Homebrew.
Finally, changed the `runtests.py` script to put quotes around all command arguments. This lets you run the tests from a path that has a space in it.
=> Fixed a spec error in the code section

ml-proto/host/js.ml
Not sure if the name $$ is always used for imports to the wrapper; I assume so.
=> Fix wrapper i64 modules

ml-proto/test/block.wast, ml-proto/test/br.wast, ml-proto/test/br_if.wast, ml-proto/test/br_table.wast, ml-proto/test/call.wast, ml-proto/test/call_indirect.wast, ml-proto/test/func.wast, ml-proto/test/loop.wast, ml-proto/test/return.wast, ml-proto/test/stack.wast, ml-proto/test/unreachable.wast
As discussed in #343, this adds `drop` to `br_if`s where necessary, and moves some stacky tests into `stack.wast`. With these changes, the "non-stacky" test files don't have stacky stuff, and binaryen can pass them (with just these disabled: stack, nop, typecheck).
=> Stack test cleanup

ml-proto/README.md, ml-proto/host/arrange.ml, ml-proto/host/js.ml, ml-proto/host/parser.mly, ml-proto/host/run.ml, ml-proto/host/script.ml, ml-proto/test/start.wast
Noticed that there was no test for traps from module instantiation. Added a new form of `assert_trap` taking a module definition.
Also refined JS translation to check that the correct exceptions are thrown.
=> Test traps from start function; check JS Error classes

interpreter/README.md, interpreter/host/main.ml, interpreter/spec/ast.ml, interpreter/spec/decode.ml, interpreter/spec/encode.ml, interpreter/spec/eval.ml, interpreter/spec/valid.ml, interpreter/test/binary.wast, interpreter/text/arrange.ml, interpreter/text/parser.mly
Mirroring
- WebAssembly/design#826 + WebAssembly/design#828
- WebAssembly/design#823
- WebAssembly/design#824
Also, reorder AST def + uses to match opcode order.
=> Binary updates for 0xD

interpreter/.gitignore, interpreter/test/loop.wast, interpreter/test/soft-fail.wast
Two commits:
- first one to update `.gitignore`, following a name change somewhere (?).
- second one: I've checked with @sunfishcode, and it seems those two tests from `loop.wast` are part of the unreachable test cases, which should only softly fail. The rationale, in both cases, is that a `br` to a loop top label is always void, and the function's end is unreachable, since we have infinite loops; so per spec, the validation error is a soft fail. Does it make sense? (SM doesn't issue validation errors for these two test cases, according to this reasoning)
=> Soft fail loop tests

interpreter/test/resizing.wast
Really a dumb request: we have these tests checked in in automation in SM, and among all the test machines they run on VMs which have less than 512 MB of memory. One of the resizing tests requests 10K pages of memory which is 625 MB of memory, so this consistently triggers out-of-memory (grow returning -1) in our infra. While we could tweak the test infra to handle this as an expected failures, it sounds like it defeats the purpose of the test itself, and we could just lower the amount of pages requested maybe? 800 pages is 50 MB, which is still a high number and works in our infra. I think the test was requesting a lot of memory in general; not sure it was testing for values above an certain implicit threshold.
=> Reduce the requested amount of pages in the biggest grow test case

interpreter/runtests.py
Usage is now
```
runtests.py [--wasm <wasm-command>] [--js <js-command>] [file ...]
```
which allows selecting tests or setting the JS command from the command line, e.g.
```
runtests.py --js 'd8 --expose-wasm' test/address.wast
```
=> Parameterise runtests script

interpreter/spec/decode.ml, interpreter/spec/encode.ml, interpreter/spec/valid.ml, interpreter/test/load-align-0.fail.wast, interpreter/test/load-align-odd.fail.wast, interpreter/test/memory.wast, interpreter/test/store-align-0.fail.wast, interpreter/test/store-align-odd.fail.wast, interpreter/text/arrange.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, interpreter/util/lib.ml, interpreter/util/lib.mli
To match the binary format. Ill-formed alignment is now a syntax error instead of a validation error, because it cannot be represented to binary.
=> Represent alignment in log2 in AST

interpreter/README.md
Updating the link to reflect recent rename in the design repository.
=> Fix broken link to semantics

interpreter/TestingTodo.md
These are the last remaining references to AstSemantics.md, which was renamed to Semantics.md in WebAssembly/design#813.
Follows #385 and #386.
/cc @jakzale @jfbastien
=> Fix broken link to Semantics.

interpreter/Makefile
A slight change seems to be needed in the makefile.
=> wasm.cmx is in _build not in current directory

interpreter/test/float_misc.wast
This PR removes exact some remaining exact nan-pattern tests because they became obsolete in  WebAssembly/design#716. Similar tests without bit pattern matching exist in f32.wast and f64.wast.
=> Remove exact nan-pattern tests

interpreter/spec/valid.ml, interpreter/test/memory.wast
=> Disallow using internal globals in constant expressions

document/introduction/index.rst
Adds intro that mainly summarises the design goals. Leaves out meta topics like design process and future features which don't belong into the spec itself.
=> Intro with design goals

interpreter/test/globals.wast
Add tests for invalid global mutable encoding value
=> Malformed tests for mutable encoding

interpreter/runtests.py
- Use `wasm.exe` instead of `./wasm` to run tests on Windows
- wasm.exe doesn't recognize paths with `\\`, which is the default separator on Windows
- Windows doesn't recognize arguments wrapped using `'argument'`, it needs to use `"argument"`
=> Allows to run test on Windows

interpreter/spec/eval.ml, interpreter/spec/eval.mli, interpreter/spec/memory.ml, interpreter/spec/memory.mli, interpreter/test/linking.wast, interpreter/test/memory.wast
...and add tests that memories/tables remain unchanged in case of error. Addresses WebAssembly/design#897
=> Check all segment bounds beforehand

interpreter/README.md, interpreter/host/flags.ml, interpreter/host/js.ml, interpreter/host/main.ml
This allows for use of the JS-converted files with alternative test harnesses.
=> Make JS harness optional and compatible with async

interpreter/Makefile, interpreter/spec/eval.ml, test/core/call_indirect.wast, test/core/memory.wast
=> Detect bounds wrap-around

test/core/br_table.wast, test/core/unreachable.wast, test/core/unreached-invalid.wast
Check that inconsistent label types are detected in unreachable code.
=> Few more checks for unreachable br_table

interpreter/spec/valid.ml, test/core/select.wast
It was indexing the operand stack from the wrong end, breaking typing of `drop` and `select`. Fixes #423.
=> Fix type checker's peek function

test/core/float_exprs.wast
Add some tests to check that the underlying platform follows the
basic NaN bitpattern rules without depending on the handling of NaNs
in the test harness or embedding environment.
=> Test NaN bitpattern rules in a harness-independent way.

test/core/block.wast, test/core/if.wast, test/core/loop.wast, test/core/unreached-invalid.wast
Also, fix a number of assert_invalid tests that weren't properly adapted when we introduced block signatures.
=> Add tests for `if`

test/build.py, test/harness/index.js
This should allow us building only interesting subsets of tests for different purposes:
- a browser vendor can build the JS and HTML tests only.
- for the website, we'll be able to build the front page (in a single HTML page) only.
I need to make sure this will interact well at least with Spidermonkey and the webassembly website gh-pages before asking for review. If other browser vendors could confirm this fits their workflow too, this would be great.
=> Test builder: introduce CLI options for specific sub-tasks

test/js-api/jsapi.js
According to https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor, if `Type(Get(importObject, i.module_name))` is not object, then we should throw a `TypeError`, not a `LinkError`. This should be the case here, since `importingModule` tries to import `("", "f")`, the passed imports object's key `""` is undefined.
@rossberg-chromium / @mtrofin, PTAL.
=> Fix test of empty module name in instanciation

test/core/binary.wast
I missed updating a few cases to version 1 in binary.wast that are meant
to test endianness.
=> Fix a few binary version tests

test/js-api/jsapi.js
Sorry, I didn't catch them because we had issues with our `promise_test` JS polyfill, and `jsapi.js` doesn't succeed as a WPT (for some unrelated reason).
@rossberg-chromium, can you please take a look? Thanks!
=> More LinkError that should be TypeError in async instanciate

interpreter/spec/memory.ml, test/core/memory_trap.wast
=> Don't affect memory on partial out-of-bounds stores

README.md
I built the html locally before I knew the gh-pages existed.  Would good to link it somewhere? 
P.S. The URL on the repository just points to `webassembly.github.io`, instead of with `/spec`.  Might be a typo.
=> Add link to gh-pages

test/core/br_table.wast
This adds a spec test for an unhandled `br_table` cause, found in wabt (https://github.com/WebAssembly/wabt/issues/389) and V8 (https://bugs.chromium.org/p/v8/issues/detail?id=6204)
=> Add br_table test that targets typed loop and void block

test/js-api/jsapi.js
Since stack is not standard, it fits oddly in a test suite for a standard.
=> Remove use of "stack" property on Error

test/core/import-after-global.fail.wast
The test was missing a global variable initializer expression, and so would fail regardless of whether the import-after-global syntax error is detected correctly.
=> Fix import-after-global.fail test

document/binary/instructions.rst, document/binary/modules.rst, document/binary/types.rst, document/binary/values.rst, document/execution/conventions.rst, document/execution/index.rst, document/execution/instructions.rst, document/execution/modules.rst, document/execution/numerics.rst, document/execution/runtime.rst, document/index.rst, document/instantiation/index.rst, document/math.def, document/syntax/conventions.rst, document/syntax/instructions.rst, document/syntax/modules.rst, document/syntax/types.rst, document/syntax/values.rst, document/validation/conventions.rst, document/validation/instructions.rst, document/validation/modules.rst
First stab at of the execution semantics. Describes conventions, runtime structures, and the semantics of instructions. Still missing: the description of the numeric operations and the instantiation/linking of modules. Various other tweaks included.
Preview at https://webassembly.github.io/spec/
=> [spec] Execution: conventions, runtime, instructions

syntax/conventions.html
A^+ can not be empty, so the description as "...possibly empty sequence of iterations..." was changed to "...non empty sequence of iterations..."
=> A^+ description changed

test/js-api/jsapi.js
This PR updates tests for `Instance.prototype.exports` to match https://github.com/WebAssembly/design/pull/1062.
=> Update tests for Instance exports property

document/appendix/implementation.rst
As discussed on https://github.com/WebAssembly/design/pull/1016, make it legal for implementations in environments that do not understand (all of) Unicode to only support smaller character subsets.
=> [spec] Allow impls to limit code point range

interpreter/Makefile, interpreter/text/parser.mly, test/core/func.wast, test/core/type.wast
Fix spec deviations:
- allow multiple results in function defs
- disallow multiple results in block sig
This is consistent with the spec document and the binary format.
=> Fix result syntax

test/harness/wasm-module-builder.js
Initially as I read the api, I thought the `end` method would well end the function, but all it does is return the module builder (which is nice for chaining).
This change simplifies how to make empty function also
```js
const builder = new WasmModuleBuilder();
builder.addFunction(null, kSig_v_v).end().instantiate();
```
instead of
```js
const builder = new WasmModuleBuilder();
builder.addFunction(null, kSig_v_v).addBody([kExprEnd]).end().instantiate();
```
This changes the behavior of the `end` method and I don't know if someone else depends on this behavior, but I checked in this repo and `end` is not used
=> Make WasmFunctionBuilder.end() append the end opcode

test/harness/wasm-module-builder.js
Spreading the section into arguments can become too long for some engines.
=> Test Harness wasm-module-builder.js allow long sections

test/harness/wasm-module-builder.js
The table index for table segments must be emitted before each segments as documented in https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#element-section
=> Test Harness wasm-module-builder.js fix table index segment

test/js-api/jsapi.js
These two tests don't make much sense to me because the string argument invokes the `length` constructor of `TypedArray`:
https://tc39.github.io/ecma262/#sec-typedarray-length
This then goes ToIndex / ToInteger etc, and the string becomes an integer.
What's the point of this test?
=> Remove odd tests

test/harness/wasm-module-builder.js, test/js-api/jsapi.js
Removed pushing `end` opcode on `.end()` since `.addBody()` now does it too.
Added test `Memory.prototype.grow(0)` with initial size 0
=> Test js-api: add memory.grow test

interpreter/text/parser.mly, test/core/func.wast, test/core/imports.wast
This PR fixes/changes identifier resolution for the text format:
1. Correctly handle forward references to type definitions, and add tests.
2. Tweak the expansion of inline function types by inserting type definitions at the _end_ of the module.
The latter should hardly affect any existing programs, because it's only observable if a program uses raw numeric type indices _and_ forward-references later type definitions with them.
See [comment below](https://github.com/WebAssembly/spec/pull/512#issuecomment-311778787) for an example.
DETAILS
All module-level symbolic names are in scope everywhere, but the interpreter did not handle forward references to type definitions correctly, and there were no tests. This PR fixes that, and handles name resolution and AST construction more consistently …
=> [interpreter/test] Fix symbolic forward references and change inline type expansion

test/js-api/README.md
Tests with assert_not_equals have been added to the test suite, see test/js-api/jsapi.js.
=> Add assert_not_equals to README.md

README.md
The current verbiage creates some uncertainty regarding the status of this repo from W3C reps, clarifying.
=> Update readme to reflect current status.

document/core/text/values.rst, interpreter/exec/int.ml, interpreter/text/lexer.mll, test/core/float_literals.wast, test/core/int_literals.wast
Allow literals like 1_000, 0xfff_ffff, 3.145_692 etc, as discussed earlier.
=> [spec/test/interpreter] Allow underscores in numbers

test/harness/wasm-constants.js, test/harness/wasm-module-builder.js
The original version of this file was a fork of the V8 module builder. This is just an update with the additional functionality that we have seen fit to add in our tests, including, e.g., the new names section format.
=> Update JavaScript WasmModuleBuilder with new functionality.

document/core/syntax/types.rst
This PR fixes a typo in the spec document.
=> Typo: Mutability in global types is mandatory

document/core/syntax/instructions.rst, document/core/text/instructions.rst
=> [spec] Fix documentation issues around `demote`/`promote`

test/core/elem.wast
The module names in the tests in elem.wast contained a "-", which is an invalid character in JavaScript variable names. Thereby the JavaScript test generated from elem.wast could not be executed anymore. This CL removes the "-" from the module names and thereby fixes the problem.
=> Fix invalid module names in test

interpreter/binary/decode.ml, test/core/float_literals.wast
This loads the u64 value in two u32 pieces, but was using
`Int64.of_int32` which sign-extends the i32 value. This causes the f64
value `4294967249` to be read as `4294965201`, for example.
Fixes #543.
=> Fix decoding of f64 binary values

test/harness/wasm-module-builder.js
Some engines have a limit to the number of arguments functions can have and there is no limit to the size of a section.
=> Harness-module-builder: Do not spread potentially big arrays as function parameters

document/core/exec/instructions.rst, document/core/text/instructions.rst
=> [spec] Fix alignment immediate in text format

document/core/appendix/index-rules.rst, document/core/appendix/properties.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst, document/core/exec/runtime.rst, document/core/util/math.def
Plus a few random typos.
This change is inspired by discussion with Conrad Watt, who pointed out a problem with the previous formulation.
=> [spec] Fix and clean up invariants for host functions

document/core/appendix/embedding.rst, document/core/appendix/index-rules.rst, document/core/appendix/index.rst, document/core/appendix/properties.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst, document/core/exec/runtime.rst, document/core/text/lexical.rst, document/core/util/macros.def, document/core/valid/modules.rst
This PR adds an appendix defining an "embedder interface", i.e., entry points that other specs like the JS API can reference to define the operations that they provide to a host environment. The intention is that this interface is complete in the sense that no other parts of the core spec (except pieces of the abstract syntax, like types and values) need to be directly referenced from an embedder spec.
Preview at: https://webassembly.github.io/spec/appendix/embedding.html
=> [spec] Add embedder interface

test/core/unreached-invalid.wast
The current tests allowed an implementation to either assume an else
block to be reachable, or inherit the reachability from it's parent
(which would be wrong).
This adds more tests for different control instructions in unreachable
code.
=> [test] Add tests for control instructions in unreachable code

document/core/binary/conventions.rst, document/core/util/macros.def
As discussed in #583.  Reading https://www.iana.org/assignments/media-types/media-types.xhtml it seems like the more modern name is "Media Type".
=> Mention suggested MIME type in Binary Format | Conventions

document/core/text/instructions.rst
This is a late but small change/extension to the text format that I floated with some people.
Instead of a simple type index, the call signature for `call_indirect` is specified using the existing `typeuse` syntax used e.g. in function declarations:
```
call_indirect (type $t)
call_indirect (param i32 i32)
call_indirect (param i32 i64) (result i32)
```
That makes it consistent with how types are/will be referenced elsewhere (besides function declarations, e.g. in block signatures in the [multi-value proposal](https://github.com/WebAssembly/multi-value/)). Furthermore, as the example shows, it implies that you can write the call signature inline, like for functions and blocks.
The expansion rules are like for function declarations. However, inline types for call_indirect must not include …
=>  [spec] Use typeuse syntax for call_indirect

test/build.py
The old subprocess API also works for python version below 3.5, and the new API is actually not needed in this script.
=> Use the old subprocess API in test/build.py

document/core/exec/instructions.rst
=> [spec] Fix block values

document/core/appendix/embedding.rst
The formal definition is correct, but the return type of the `read_table` embedding function in the prose misses the optional sign.
=> [spec] read_table returns an optional function address

document/core/exec/instructions.rst
Strictly speaking, the mapping only covered unary operators. This tweak generalises to n-ary.
=> [spec] Minor tweak to op mapping

document/core/exec/modules.rst
The old rule returned a frameless configuration, which did not match
how `invoke` is used. (The `invoke_func` function in the appendix
simply starts reducing from whatever `invoke` returns.)
Any frame will do.
=> [spec] Make the `invoke` function return a full machine configuration

document/core/exec/instructions.rst
A successful `grow_memory` had been able to return any `sz`.
The `call` instruction didn't honor result types.
=> Simple fixes to `call` and `grow_memory`

document/travis-deploy.sh
There was an errant call to "bash" at the end of the Travis CI deploy
script, leading deploys to stall and appear to be failing. This patch
removes the line.
=> Fix build issue

document/core/exec/runtime.rst
Replace frame instructions in evaluation contexts with a
context-sensitive structural rule.
Clarify the side-condition in the trap propagation rule.
=> [spec] Fix evaluation contexts and structural rules

document/js-api/index.bs, test/js-api/jsapi.js
Normative: Re-exported host functions are numbered
The first patch patch makes the names of exported functions which come from
imported host functions be the index of the import. Although it
was a bit implicit in the original JS.md specification, this are
probably the originally indended behavior.
These semantics seem to be implemented by V8 and SpiderMonkey, but
JSC supports different semantics for exported function names.
----
[test] JS API tests for caching and function names
The second patch add tests against the WebAssembly JS API for
- Memory, tables and functions, including JS FFI functions, are
cached and reused between imports and exports.
- The name property of functions is determined by the index where
they are defined; for JS functions, this is the index where
they are …
=> [spec,test] Host function name specification; tests for function names and caching

document/js-api/index.bs
This way the counts won't go out-of-sync with their associated lists.
See comment here: https://github.com/WebAssembly/spec/pull/653#discussion_r164284778.
=> Remove explicit counts in JS API spec

interpreter/host/spectest.ml, test/core/func_ptrs.wast, test/core/globals.wast, test/core/imports.wast, test/core/linking.wast, test/core/memory.wast, test/core/names.wast, test/core/start.wast, test/harness/index.js
This just updates the testsuite, and does not update the interpreter.
=> Rename spectest imports to avoid depending on overloading.

document/core/appendix/index-rules.rst, document/core/appendix/properties.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst
Change expression evaluation to reduction. The use of `\stepto^\ast` in the evaluation rule's conclusion had been confusing, being syntax rather than the usual RTC operator.
Fix an incidental typo in `_index-rules`. The instruction reduction judgment lacked an `^\ast`.
Remove unused details from the rules for `\instantiate`. Neither `\globaladdr^\ast` nor `k` was used.
Make `\instantiate` prose and rules agree on when to trap by dropping the generic "otherwise" rule that trapped. The rules no longer relate inputs to outputs where the prose specified "Fail". (Aside: nothing had to change in the embedding, where instantiation is used.)
Make `\instantiate` check, rather than assume, validity of inputs.
Update `\instantiate` prose to use `allocmodule`.
Note the mutual recursion between …
=> [spec] Clean up instantiation and expression evaluation.

test/js-api/jsapi.js
The addBody function of the WasmModuleBuilder automatically adds kExprEnd at the end of a function. Explicitly adding kExprEnd at the end of a function therefore causes the generated code to be incorrect WebAssembly code. This PR removes such an explicit kExprEnd.
=> Remove redundant kExprEnd in test

document/core/appendix/properties.rst, document/core/util/macros.def
Cite Conrad Watt's CPP 2018 paper describing the Isabelle mechanisation of the soundness proof.
=> [spec] Cite mechanisation paper

document/travis-deploy.sh
Submitting TBR, trying to figure out why travis is failing to correctly update.
=> Turn on logging to help debug travis failures.

interpreter/script/js.ml
This PR gets the JS  tests generated by the spec interpreter in sync again with the changes done in https://github.com/WebAssembly/spec/pull/652.
=> [test] Sync default imports of the interpreter with the test harness

interpreter/script/js.ml
This PR fixes the problem discussed in https://github.com/WebAssembly/spec/issues/684. We wrap the default imports in the core spec tests to avoid TypeErrors, because in the core WebAssembly spec TypeErrors have no place.
Drive-by change: add newlines I forgot in the last PR.
=> [test] Wrap the default imports in a proxy to avoid TypeErrors

document/core/syntax/modules.rst
Add a note clarifying that import names are not unique, and remove a contradicting statement. Addresses #622.
=> [spec] Clarify overloaded imports

document/js-api/index.bs, test/js-api/jsapi.js
Includes a test to verify. Test passes on V8.
Closes #647
=> [spec] Normative: Clarify that JSAPI i32 conversions are signed

document/js-api/index.bs, document/web-api/index.bs
In particular, the spec moved and redirects don't seem to be in place;
this patch fixes the links.
=> [spec] Editorial: Fix cross-references to core spec

document/core/exec/numerics.rst
fne is the invert of feq. Hence, it returns 1 if either operand is NaN.
This matches the spec tests and the behaviour of the reference interpreter.
=> Fix spec for fne (returns 1 for NaN)

test/js-api/jsapi.js
According to the spec, exported functions should not have a [[Construct]] method, hence they should not have a prototype.
=> Test that exported functions have no prototype

interpreter/text/parser.mly, test/core/call_indirect.wast, test/core/stack.wast
=> [interpreter] Fix flat call_indirect

test/html/indexeddb.js
The .addBody function of the WasmModuleBuilder automatically adds kExprEnd at the end of a function. Therefore the explicit addition of kExprEnd produces invalid wasm code. If you want to add kExprEnd explicitly, you have to use .addBodyWithEnd.
=> [test] Remove redundant kExprReturn

test/harness/index.js
This is the same change I did already for the core spec tests (#685), but this time for the multi-stage testing.
Original message:
This PR fixes the problem discussed in #684. We wrap the default imports in the core spec tests to avoid TypeErrors, because in the core WebAssembly spec TypeErrors have no place.
=> [test] Fix default imports in the multi-stage tests

interpreter/binary/decode.ml, test/core/binary.wast
=> [test/interpreter] Fix LEB128 check for unused bits; add tests

test/core/unreached-invalid.wast
This code is working as:
1. `unreachable`: makes the stack polymorphic.
2. `br_if`: Pops condition (always i32) and block's "label" values (in this case i64). Since stack is polymorphic and is empty this values might be represented as `Unknown` in validation algorithm. Then the "label" values are pushed on back on the stack.
3. `i64.extend_u/32`. Pops i32 value and extends it to i64 and pushes it on the stack.
Because `br_if` (2) can be viewed as a kind of tee (pop the value and push it back), it might be implemented in way that it pushes the value with type that was popped from the stack rather than pushing the value with type specified by the block. 
The problem with this approach is the stack value might be `Unknown` and the type pushed after it will be `Unknown`, and in (3) value …
=> Add type-br_if-after-unreachable test.

test/core/imports.wast
Check that if function import descriptor referres undefined type then the module is invalid.
=> [test] Import referring undefined type is invalid

interpreter/binary/decode.ml, interpreter/util/lib.ml, interpreter/util/lib.mli
Avoid bogus length check when decoding local count. Also, make some library functions tail-recursive to avoid stack overflow.
=> [interpreter] Fix local decoding

document/core/util/katex_fix.patch
Removes extra border on footnotes.
Fixes:
https://github.com/WebAssembly/spec/issues/673
=> Fixing borders + gray bar.

document/js-api/index.bs
Detaching an ArrayBuffer which comes from a WebAssembly.Memory
throws an error. Previously, this was simply asserted in a comment;
this patch hooks into a new ECMAScript layering device to make
things more clear.
Depends on https://github.com/tc39/ecma262/pull/1112
=> [spec] Layering: Improve way of throwing on detach

document/core/appendix/algorithm.rst
In `pop_ctrl()`, the control stack cannot be popped first since `pop_opds()` calls `pop_opd()` which accesses the top of the stack.
=> [spec] Fix bug in validation algorithm

document/core/text/modules.rst
Seemed to be duplicated from the math section above it, but never rendered because it is invalid.
=> [spec] Remove invalid math section

document/core/syntax/modules.rst, document/core/valid/modules.rst, document/js-api/index.bs, interpreter/script/js.ml, interpreter/valid/valid.ml, test/core/globals.wast, test/core/linking.wast, test/harness/wasm-module-builder.js, test/js-api/jsapi.js
We discussed this in the June 6 Working Group meeting and decided to merge the mutable-global proposal into v1 of the spec.
Since this proposal doesn't actually change that much, I thought it might be nicer to squash the changes from the mutable-global repo it into one patch. This means we lose the change history here, but it's still available in the mutable global repo, so I think it's OK. What does everyone think?
=> Merge mutable global proposal into spec

document/js-api/index.bs
See discussion in issue #816. In the future, we'll want to store
non-numeric values in a `WebAssembly.Global` object, so using
`unrestricted double` is over-constrained.
=> [spec] Use `any` in `Global` constructor

interpreter/binary/decode.ml, interpreter/util/lib.ml, interpreter/util/lib.mli, test/core/binary.wast
Adds a test that there can be no more than 2^32 locals defined in a binary.
Adds a fast failure path for this case in the interpreter.
Addresses #823 and subsumes #824.
=> [test/interpreter] Check for max number of locals

document/js-api/index.bs, document/web-api/index.bs
- Fix accidentally setting the wrong state from Table.grow
- secondName -> sectionName
- Fix note about NaN payloads
- Improve name of some types
- Make proper use of byte stability
- Create a promise from within "asynchronously compile..."
Fixes issues reported in #730 
cc @erights
=> [js-api] Fix various style issues and typos found by Mark Miller

document/web-api/index.bs
This patchset adds support to WebAssembly.Module to be used in HTML serialization, including from `postMessage` and IndexedDB. The change is based on @flagxor 's [earlier PR](https://github.com/WebAssembly/design/pull/1074), with the following changes:
- Rather than actually including the Module in the serialization, this PR includes only the binary data, as the Module cannot be referenced across agents (which each have their own separate store).
- The same-agent-cluster limitation is removed, as it is nonsensical in the context of *forStorage* serialization, for example IndexedDB, which is permitted by this specification.
- The Memory aspects are omitted in this PR; those will be pursued in a separate PR in the threads repository.
- The bytes of the module are explicit …
=> [spec] Normative: Support [Serializable] for WebAssembly.Module

document/js-api/index.bs
=> Allow creation of default i64 global values

test/core/address.wast
Current address.wast only cover partial load operators with
different offset and align combinations, this PR fulfills
the rest operators with consistent combinations
=> [test] Enhance test coverage of address.wast

test/Todo.md, test/core/memory_grow.wast
- Covers checkpoint at Todo.md:
test that newly allocated memory (program start and memory.grow) is zeroed
- rename resizing.wast to memory_grow.wast
=> [test] Grow memory and verify that new allocated byte is zero

test/Todo.md
Following 3 checkpoints have been tested in [memory_grow.wast(L36-L60)](https://github.com/WebAssembly/spec/blob/master/test/core/memory_grow.wast#L36), [memory.wast(L52-L75)](https://github.com/WebAssembly/spec/blob/master/test/core/memory.wast#L52), [align.wast(L436)](https://github.com/WebAssembly/spec/blob/master/test/core/align.wast#L436) respectively
- test that too-big `memory.grow` fails appropriately
- test that too-big linear memory initial allocation fails
- test that an i64 store with 4-byte alignment that's 4 bytes out of bounds traps without storing anything.
=> [test] Remove tested checkpoints in Todo.md

test/Todo.md, test/core/align.wast
- test that an i64 store with 4-byte alignment that's 4 bytes
out of bounds traps without storing anything
=> [test] Add test to cover one checkpoint in Todo.md

document/js-api/index.bs
They need four spaces rather than three to escape from the parent list.
=> Indent substeps correctly in the Global constructor.

test/core/br_table.wast
the func is intended to use br_table as a br value
=> [test] Fix a minor issue in br_table.wast

document/core/valid/instructions.rst
This appears to me like a copy&paste error (coming from `block`'s note). You don't actually use this notation here. You use a simpler version with the empty sequence label type. While this is not wrong as written (for `t^?` is allowed to be empty) it is confusing. But feel free to close if I am mistaken.
=> Potential copy&paste error in loop's note

document/core/Makefile, document/core/util/README.htmldiff.pl, document/core/util/htmldiff.pl
This uses the same htmldiff script as found in the w3c HTML diff
service: https://services.w3.org/htmldiff
To diff locally, run: `make diff` in the core directory.
=> Add script to diff HTML against previous version

document/core/valid/modules.rst
These are no longer true, now that the mutable-globals proposal has been
merged into the spec.
=> Remove immutable global notes

test/harness/wasm-module-builder.js
Bring wasm-module-builder.js in sync with the version in V8.
=> [test] Update wasm-module-builder.js

document/js-api/index.bs, document/web-api/index.bs
This changes the specification to consistently grab the bytes immediately upon
receiving a BufferSource from user code, and store bytes directly in the
[[Bytes]] field.
This also clarifies the parsing of custom sections from the module bytes.
=> [js-api] Fix some inconsistencies around handling bytes and buffers.

test/core/binary.wast
Just a small fix to the `binary.wast` test script. In a couple of assertions, the binary module has the wrong size in the memory sections
=> Fix memory section length

test/core/call.wast, test/core/call_indirect.wast
- Partial funcs(e.g. $over-i32-duplicate) without tests covered
- Add tests for call/call_indirect as param of control constructs/instructions
@rossberg, PTAL. Thanks!
=> Improve test coverage of call_indirect.wast and call.wast

test/core/binary.wast
`call_indirect`, `memory.grow`, and `memory.size` all require the
memory/table index to be a single zero byte.
These tests ensure that the index is not being parsed as a LEB128, which
can encode zero as two or more bytes: `0x80 0x00`, `0x80 0x80 0x00`,
etc.
=> [core test] Reject "long" LEB128 reserved bytes

test/harness/wasm-constants.js, test/harness/wasm-module-builder.js, test/js-api/jsapi.js, test/js-api/limits.js
This matches the nomenclature of the spec.
Also:
* Remove the `function_table` array from `wasm-module-builder.js` which
is not used.
* The `appendToTable` function should reference
`function_table_length` instead of `function_table.length`.
=> Use "Element Segment" terminology in js-api tests

document/js-api/index.bs
In particular, this ensures that the [[ArrayBufferDetachKey]] slot is always set (fixes #855).
=> [js-api] Introduce a 'create a memory buffer' algorithm.

document/js-api/index.bs
Notes the goals of #879
Also change the name of the grow_memory instruction to memory.grow
=> Editorial: Note status of memory growth errors

test/core/binary.wast
The spec says that a data/element segment are required to have a `0` for
the memory/table index, but they can be written using a long encoding,
like `0x80 0x00`.
=> [core test] Tests long encoding of a segment index

document/js-api/index.bs
JS/Web specs use mutable lists as a common data structure, whereas
the WebAssembly core specification uses a logical (immutable) sequence
data structure. This patch explicitly converts from a list to a
sequence to reduce ambiguity.
=> Editorial: Explicitly convert between list and sequence

test/core/labels.wast
Fixed: function "br_if2" doesn't actually use `br_if`
=> Correct "br_if2" function in labels.wast

document/core/binary/values.rst
Rule out U+DC00..U+DFFF in the utf8 function, which was missing in the spec.
=> [spec] Properly rule out surrogate codepoints

test/core/binary.wast
It is a validation error if the function section is present, and has a
non-zero count, and the code section is missing. However, if either
section has a zero count, then the other section may be absent.
=> [core] Test function/code count mismatch

test/README.md
The directories built by the build.py script aren't checked in in the
repository, so don't try to link to them.
=> Remove link in test's README and update WPT link

document/core/binary/values.rst
Continuation bytes must not have bot 6 set.
=> [spec] Add missing UTF-8 side condition

test/build.py
The build tool can't handle the current js-api tests, and would take a
significant rewrite to do so. In particular, it would need to stop handling the
helper .js files as tests, and ensure they are included when running the tests
that need them.
However, all of this is already achieved without a build step in the wpt context
as well as in the integration into SpiderMonkey's jstests harness. This
suggests that trying to handle these tests in the build script is not
necessary.
=> Stop trying to build js-api tests.

test/build.py
readlines() returns a list of strings, each of which will still have the EOL
character at the end, so this code added an empty line between every line in
the original file. This commit simplifies the code to avoid that.
=> [test] Stop using readlines() in wrap_single_test().

test/core/br.wast, test/core/i32.wast, test/core/if.wast, test/core/return.wast
- br.wast: "$type-operand-missing" and "$type-operand-missing-in-block"
are similar to "$type-arg-empty-vs-num"
- return.wast "$type-operand-missing" is similar to "$type-value-empty-vs-num"
- if.wast: no duplicates
=> [test] Remove duplicated tests

.gitmodules, document/core/Makefile, document/core/util/katex_fix.patch, document/core/util/mathjax2katex.py
This includes a fix for italic fonts.
Running katex from the commandline has a dependency, so `npm install`
must be run.
See issue #669.
=> Update katex to v0.10.0

document/js-api/index.bs, test/js-api/module/customSections.any.js
Switching from USVString to DOMString will allow the string to contain non normalized surrogates.
Currently, JavaScript engines already use a DOMString as argument.
Fixes #915 
cc @Ms2ger @littledan
=> [js-api] use DOMString

document/core/syntax/instructions.rst
=> [spec] Provide context to `break` analogy

document/core/syntax/instructions.rst
Addresses [this comment](https://github.com/WebAssembly/spec/issues/884#issuecomment-458915170).
=> [spec] Fix comment still referring to old syntax

interpreter/script/js.ml
Makes the harness much easier to read and edit. :)
=> [interpreter] Use literal string for JS harness

test/core/br.wast, test/core/i32.wast, test/core/if.wast, test/core/return.wast
This is the second part to fix following task in typecheck.wast:
;; TODO(stack): more of the above
=> [test] Add more tests for operand missing -Part2

test/js-api/limits.any.js
Caches the generated Wasm buffer instead of re-generating
it for each test.
Refs https://github.com/WebAssembly/spec/issues/972
=> [jsapi] update limits.any.js

test/js-api/wasm-module-builder.js
This speeds up the WasmModuleBuilder enormously. It follows this V8-side
CL: https://crrev.com/c/1508352
It also adopts a few other minor changes to the wasm-module-builder.js
file from the v8 side.
=> [jsapi] Update wasm-module-builder.js

test/js-api/module/customSections.any.js, test/js-api/wasm-module-builder.js
Updating the wasm-module-builder.js broke the jsapi tests. I was under
the impression that travis would run them, but it seems like this is
not the case. Rolling the updated version to v8 failed then:
https://crrev.com/c/1516684
This fixes two things:
1) {toBuffer} returns a Uint8Array as before, not an ArrayBuffer,
2) {addExplicitSection} expects a byte sequence, hence pass the
truncated buffer instead of the {Binary} object.
=> [jsapi] Fix tests after wasm-module-builder.js update

document/js-api/index.bs
The store variable was not defined before it was used, and the result was not
saved.
=> Fix store handling in 'instantiate a WebAssembly module'.

document/js-api/index.bs
=> Reject the promise if reading the imports fails.

test/core/select.wast
The full error message generated by the interpreter is "unreachable executed", but all of the other tests check for just "unreachable".
=> [test] Check for "unreachable" consistently

test/core/linking.wast
The start function is invoked after the store has been modified. So if a
start function traps, all data and element segments will have been
copied into the memory and table respectively. This means that functions
can be invoked on this instance, even though the instance is not
available to the embedder directly.
See issue #993.
=> [test] Add test when start function traps

document/core/appendix/embedding.rst, document/core/appendix/implementation.rst, document/core/binary/values.rst, document/core/intro/introduction.rst, document/core/syntax/values.rst, document/core/text/conventions.rst, document/core/text/lexical.rst, document/core/text/values.rst, document/core/util/macros.def
Say "scalar value" instead of "code point" (renaming grammar symbol to `char`). Fixes #1000.
=> [spec] Use more precise Unicode terminology

document/core/appendix/embedding.rst, document/core/appendix/index-rules.rst, document/core/util/macros.def, document/core/valid/types.rst, document/js-api/index.bs
This makes explicit the difference between assertions and pre-conditions in the embedding interface. Also adds post-conditions and missing pre-conditions, including some additional conventions to avoid clutter.
Moreover, switch some function names around to consistently use the form `kind_op` (e.g., `module_decode`) instead of the mix before. This is more uniform and matches the onventions used in the C API.
=> [spec] Preconditions and some renamings in embedding interface

document/core/util/macros.def
We are using local \def for macros due to Sphinx limitations, but Latex does not like that in captions. So avoid some of those macros.
=> [spec] Work around Sphinx/Latex issue

document/core/exec/modules.rst
Table size must not reach 2^32, otherwise it is no longer representable. Check was off by one.
=> [spec] Fix table grow size limit

document/core/index.bs, document/core/util/mathjax2katex.py
A recent change caused the generated html to have a sequence that looked
like `{{abkasdfadsf}}`, which bikeshed misinterprets as a WebIDL markup
shorthand. Since we never use that shorthand in the core spec, we can
disable it.
Since bikeshed thought this was a IDL reference, it inserted an
additional `<code>` tag, so the `mathjax2katex.py` script was not able
to extract the math blocks properly. The `FindMatching` function was
raising an `IndexError`, but it was never caught and instead terminated
the worker thread. The main thread would then wait forever for a worker
thread that will never finish. The fix here is to catch all exceptions
and print an error, instead of just catching `KeyboardInterrupt` and
`AssertionError`.
=> Fix bikeshed build

document/core/appendix/implementation.rst, document/core/appendix/index-types.rst
Includes commit from #1011
Addition:
It originally states that `0x7C` is both `f64` and `(reserved)`, changes range from `0x7C .. 0x71` to `0x7B .. 0x71`
=> Very small typo #2

document/core/appendix/embedding.rst
It seems Sphinx and ReST allow you to use any underline pattern for
sections, but assign their number ordinally as they're encountered.
So when PR #1003 intrdouced a new section in A.1 Embedding using "...",
it becomes `<h4>`, and changes the meaning of the other sections,
creating a strange ToC.
=> [spec] Fix ToC of Appendix in w3c version

document/js-api/index.bs
Replace `init_store` with `store_init`.
Also, reword the "Security and Privacy Considerations" section, and fix
the references are using ReST syntax (which doesn't work in bikeshed).
=> [spec][js-api] Fix some links

document/js-api/index.bs
This follows the convention followed by the JavaScript spec and HTML.
Fixes #1026
=> Editorial: Remove links from Number, Object when checking types

test/core/binary.wast
for type, import, export, table, memory, global, element/data segment,
and br_table.
=> [test] Add more inconsistent length tests in binary.wast

document/js-api/index.bs
=> [js-api] Remove incorrect note about object caching.

interpreter/exec/f32_convert.ml, interpreter/exec/float.ml, interpreter/exec/i64_convert.ml
Since some distros are still stuck on Ocmal 4.02, and we only use very few newer features, downgrade those and add respective comments.
=> Downgrade to Ocaml 4.02

document/core/util/bikeshed_fixup.py, document/core/util/macros.def
A new 2019 revision of the  IEEE 754 standard has been released: http://754r.ucbtest.org/background/
It's just a minor revision, and none of the listed changes affect Wasm, so this merely updates the reference.
=> [spec] Upgrade to IEEE 754-2019

document/core/appendix/algorithm.rst, document/core/syntax/instructions.rst, interpreter/Makefile
Properly use "instruction" not "operator" in a couple of places.
=> [spec] Terminology nits

interpreter/exec/float.ml, interpreter/text/arrange.ml, test/core/run.py
Improve text format pretty printer such that text/binary roundtrips are idempotent:
* Fix bug with alignment shorthand being based on wrong size.
* Increase precision for printing float literals.
* Don't sort imports.
* Normalise input binaries.
Test runner now checks that roundtrips produce the exact same files after the first step. Also, re-run script after conversions, do not just re-validate.
Fixes #1054.
=> [interpreter] Make roundtrips perfect

interpreter/Makefile, interpreter/meta/jslib/build.sh
Tweak build script for wast.js to work with current BuckleScript.
Should fix # #1052, #1055, #1056.
=> [interpreter] Update BS support

.travis.yml, document/core/Makefile
It was broken due to the accidental submodule update in #1034.
=> Fix the katex build on Travis.

document/core/text/values.rst, interpreter/exec/float.ml, test/core/const.wast
Fixes #1066. Also fixes a recent bug in interpreter's double rounding mitigation and adds parsing tests.
=> [spec] Fix float text format

test/core/elem.wast
One test in elem.wast expects the trap message "uninitialized element 7",
which requires wasm runtimes to be able to print the element index. This
is obviously nice for humans, but can be inconvenient to implement in wasm
implementations which use signals to implement traps, as it requires special
code to preserve the element index.
Other tests eg. in imports.wast don't include the number in the expected
message.
It seems better to allow implementations to decide for themselves
whether to print the index number, rather than having it be an outright
requirement of the spec test.
=> Don't require the element index in "uninitialized element" trap strings.

test/build.py
convert_wast_to_js uses multiprocessing to parallelize compilation of
wast test cases. When an error happens, the logging code expects the
result to be a process exit code and a CompletedProcess instance.
This isn't possible, so this commit updates the result to be a
CompletedProcess and modifies the code to manually check the exit code.
=> [test] Fix error in build.py when test compilation fails

test/core/call_indirect.wast, test/core/data.wast, test/core/elem.wast
Similar to #1076, don't include index numbers in expected error messages
from validation. This allows implementations to avoid creating
dynamically formatted strings for validation error messages. Admittedly
this isn't a huge burden, but it does seem like something that shouldn't
be required to pass the spec test.
=> Dont expect indices in validation messages either.

test/core/i32.wast, test/core/i64.wast, test/core/names.wast, test/core/unreachable.wast
This tests that `div_s` produces the expected trap in a corner case, more interesting Unicode characters, and an `if-else` + `unreachable` combo that wasn't previously covered.
=> Miscellaneous tests

test/core/if.wast
These tests also include a typing error that would cause them to fail validation.
I've open an issue about whether the tests should distinguish between malformed and invalid [here](https://github.com/WebAssembly/spec/issues/1040), but independent of the outcome of that issue, I think these tests should be changed to be valid apart from their malformed syntax.
=> Fix some assert_malformed module tests to ONLY include malformed syntax

interpreter/exec/eval.ml
according to
https://webassembly.github.io/spec/core/exec/instructions.html#exec-return
the `Return` instruction pops the top of the stack, until the next
frame. The equivalent in the reference interpreter should be to set
the value stack to `[]`. This is what is happening for `Break` as well.
So for consistency, also do it here.
This has no visible effect: If the first instruction is `Returning`, the
stack is ignored everywhere. So this is purely cosmetic.
(I am only 80% sure; if not I hope to at least learn something here.)
=> Reference interpreter, step Return, clear stack

document/web-api/index.bs
The URL points to latest spec draft so it should be just ECMAScript and not ES2018. This also make it consistent with [WebAssembly JS API Normative Reference](https://www.w3.org/TR/2019/PR-wasm-js-api-1-20191001/#normative)
=> [web-api] Editorial: Remove a year from the ECMAScript Language title in normative reference

document/web-api/index.bs
closes WebAssembly/design#1202
I haven't done a build but tested the `<dl/>`s in github markdown. Please make sure this doesn't offend aasthetes or rupture eyeballs.
=> Added media type registration

document/js-api/index.bs, test/js-api/limits.any.js
Per discussion in #1116, the limit for initial memory pages remains at
32767 (just under 2GiB), while the limit for maximum memory pages is
increased to 65536 (4GiB).
Spec tests are brought in line with these definitions (they actually did
not reflect the spec text before).
Fixes: #1116.
=> [js-api] Bump limit for maximum memory size to 4GiB

test/build.py
The `text` parameter (added in Python 3.7) is simply an alias for `universal_newlines` (added in Python 3.5), which we are already passing.  Remove the duplicate keyword argument to allow tests to generate on Ubuntu 18.04, which has Python 3.6.
=> Allow test compilation on Python 3.6

document/core/text/modules.rst
In [`exportdesc` text format syntax definition](https://webassembly.github.io/spec/core/text/modules.html#text-exportdesc), links to indices (`funcidx`, `tableidx`, `memidx`, `globalidx`) are linked to [the definitions in binary format](https://webassembly.github.io/spec/core/binary/modules.html#indices). If I'm correctly understanding the spec of text format, this seems a mistake. They should be linked to [the definitions in text format](https://webassembly.github.io/spec/core/text/modules.html#indices).
This PR fixes the links.
=> [spec] Fix links to indices in exportdesc text format syntax definition

.travis.yml, document/core/util/bikeshed_fixup.py, document/core/util/mathjax2katex.py, test/core/run.py
Bikeshed requires 3.7, see
https://github.com/tabatkins/bikeshed/issues/321#issuecomment-601295711
I don't think we can run both 2.7 and 3.7 in travis, we will need to to use 2 different versions of bikeshed, but no way to specific which version of bikeshed in which version of python (could be wrong).
=> Set travis env to Python 3.7

test/harness/async_index.js, test/harness/sync_index.js
The following test was failing in SpiderMonkey:
(module $Global
(export "e" (global $g))
(global $g i32 (i32.const 42))
)
(assert_return (get "e") (i32.const 42))
The issue was a generated call to index.js `get` which would return the
exported WebAssembly.Global object and compare it to a literal 42.
The harness emitted by js.ml seems to include this check. Not sure why
that's a separate harness, but for now it seems good to have the check
in all harnesses.
=> [test] Get the value of a WebAssembly.Global in JS test_harness

document/core/util/mathjax2katex.py
1. shelve.DbfilenameShelf no longer has has_key, use `in`
2. dict no longer has iteritems(), use items()
3. open subprocess as text, since we are passing text to it
This will fix the errors mentioned in https://github.com/WebAssembly/spec/pull/1151#issuecomment-603961826
=> Fix python3 incompatibilities in script

document/core/Makefile, document/core/util/mathdef.py
latex_paper_size is deprecated since 1.6.1 [0]. Also add override
keyword when adding node to silence the warnings.
[0] https://www.sphinx-doc.org/en/master/changes.html#id100
=> Clean up deprecated options, silence warnings.

document/core/exec/runtime.rst
=> [spec] Fix typo in rule

interpreter/valid/valid.ml, test/core/memory.wast, test/core/table.wast
Remove bogus signed i32->i64 conversion on limit values and fix upper limit for table size. Add tests for table limits.
Fixes #1158.
=> [interpreter/test] Table limits

.travis.yml, document/core/util/mathdef.py, document/core/util/mathdefbs.py
Couple of breaking changes due to the Sphinx upgrade, requiring fixes:
1. node['latex'] is an invalid access. It was used when Sphinx created
custom math nodes for the math role. But now that docutils supports it,
we don't need to do this anymore.
2. we copied latex_visit_math and latex_visit_displaymath from sphinx's
LaTeXTranslator visit_math and visit_math_block, we can't call them
directly because those call respective superclass methods, and since we
call add_node, it will override those methods with ext_latex_visit_math,
and ending up in a stack overflow.
3. directly create a math node rather than calling into docutils
math_role, because it only looks at raw_text, and overrides text,
which contains what we care about (latex code).
4. Similar changes to mathdefbs
Finally we can pin …
=> Upgrade Sphinx to 2.3.0 and fixes to extensions

.travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> No longer need to specify sudo

document/core/Makefile, document/core/conf.py
With the Sphinx upgrade in #1157 we no longer need these sed commands.
At the same time, clean up the way we configure mathjax, using a config
value, instead of sed.
=> Remove sed commands to change mathjax url

document/core/conf.py
When we upgraded Sphinx, the MathJax version changed, which has a
different way of configuring TeX options. This resulted in TeX's
maxbuffer not being set right, and so processing stopped.
Fixes #1166
=> [spec] Fix TeX maxbuffer option for MathJax

interpreter/meta/travis/build-test.sh
With #1162, we install ocaml via apt, not via our download script, so we
no longer need to modify the PATH to find ocaml.
=> Remove unneeded PATH modifications

document/core/util/mathdef.py, document/core/util/mathdefbs.py
Instead of overwriting the nodes, we extend the translators provided by
Sphinx, and customize the visit_math and visit_math_block logic, to do
our hyperlinking logic before calling the base class visit methods. This
allows us to deduplicate the logic we copied earlier.
For mathdefbs.py, remove all latex related logic, since we don't use
this extension to build latex.
Issue #1157
=> Extend the HTML and LaTeX translator

document/js-api/index.bs, test/js-api/limits.any.js
As agreed upon in the CG meeting earlier this week, we can allow 4GB in both the initial and maximum memory sizes, and not just the maximum.
Followup to #1121 which raised the limit to the initial size.
=> [js-api] Bump limit for initial memory size to 4GiB

document/core/exec/modules.rst, interpreter/README.md, interpreter/exec/float.ml, interpreter/exec/i32.ml, interpreter/exec/i64.ml, interpreter/exec/int.ml, interpreter/text/arrange.ml, interpreter/util/lib.ml, interpreter/util/lib.mli
Add a specification of the subset grammar produced by binary (.bin.wast) conversion. In particular, this grammar excludes meta commands, textual or quoted modules, and non-hex or imprecise values.
Accordingly, change interpreter to produce hex floats and numbers in binary output mode and omit quoted modules.
=> [interpreter] Strictify and specify .bin.wast format

document/core/text/values.rst, test/core/const.wast
Fixes WebAssembly/design#1337.
=> [spec] Fix grammar for fractions

test/core/address.wast
There are already tests for effective address overflow, but those have a
large value baked into the offset. These tests all use `1` as the
immediate offset, and use `-1` for the address on the stack, which may
be compiled differently.
=> Add more address overflow tests

test/core/stack.wast
We've recently found a bug in a WebAssembly library we've been working
with where we're mapping WebAssembly to a tree-like IR internally. The
way we parse into this representation, however, has a bug when the
function isn't itself tree-like but rather exibits properties that
exploit a stack machine. For example this isn't so straightforward to
represent in a tree-like fashion:
(import "" "a" (func $foo))
(import "" "b" (func $foo (result i32)))
(func (result i32)
call $b
call $b
call $a
i32.xor)
The extra `call $a` in the middle is valid `WebAssembly` but needs
special treatment when converting to a more tree-like IR format. I
figured it'd be good to ensure there's a spec test covering this case as
we currently pass the suite of spec tests but still contain this bug!
=> [test] Add a test for non-treelike behavior of stack

document/core/binary/instructions.rst
Address comment in https://github.com/WebAssembly/spec/pull/1144#issuecomment-629550300.
Looks like this now.
=> Move sign-extension-ops before saturating truncation ops.

document/js-api/index.bs
Follow-up from d0afee821ef898e4b654265ec87e1df72de3e231.
=> [js-api] Fix some stray pseudo-ASCII characters.

document/js-api/index.bs
'return' is an ES-internal type; I meant to use 'normal'.
=> [js-api] Fix assertion in 'create a host function'.

document/js-api/index.bs
This PR resolves an inconsistency of implementation-defined limits in the js-api specification, and execution limits in the core specification. The core specification requires under [execution limits](https://webassembly.github.io/spec/core/appendix/implementation.html#execution) that implementations throw a runtime error if tables or memories grow beyond an implementation-defined limit. The js-api specification, however, required a compile error if the module defines limits beyond the implementation-defined limits.
This PR resolves this inconsistency by adjusting the js-api specification. For the maximum memory size and maximum table size, a RuntimeError is now required instead of a CompileError.
=> Inconsistency of implementation-defined limits

.travis.yml, interpreter/README.md, interpreter/exec/f32_convert.ml, interpreter/exec/float.ml, interpreter/exec/i64_convert.ml
Fix deprecated warnings for String.uppercase (deprecated since 4.03.0) and Pervasives (deprecated since 4.08.0). Breaks compatibility with OCaml < 4.07.0. If compatibility is required, [stdlib-shims](https://github.com/ocaml/stdlib-shims) could be used.
=> [interpreter] Fix compilation warnings; upgrade to OCaml >=4.07

test/core/binary.wast
This test doesn't really test what it says: the br_table is consumed
correctly, and instead the `end` instruction is missing. This has caused
various issues in decoders (see issue #1170) as well as requiring
changing the error message in future proposals (e.g. bulk memory).
=> [test] Remove br_table binary test

test/js-api/wasm-module-builder.js
This was fixed in v8 (the source of this file) in
https://crrev.com/c/1995272.
=> [test] Fix endianness problem in wasm-module-builder.js

test/core/conversions.wast
I may be missing something here, sorry if so. Looks like the
existing tests check for `2147483647.0` and `2147483648.0`,
but not the precise fraction where things change. I think that
is fully defined by the spec, so it should be testable?
I noticed this as the binaryen fuzzer found a difference between
the binaryen interpreter and other VMs, so I assume the spec
interpreter is right and these tests are valid?
=> Add more i32.trunc_f64_s conversion checks

document/core/exec/numerics.rst
=> [spec] Fix sqrt(-0)

test/core/binary.wast
This adds explicit tests for "invalid section id". Previously there was only single test for it in custom.wast.
Some of the test cases are designed in a way to reproduce issues of parsing section ids as LEB128 encoded values.
This reproduces the bug in [wabt](https://github.com/WebAssembly/wabt) fixed by https://github.com/WebAssembly/wabt/pull/1501.
The bug has been discovered by fuzzing wabt wasm validation against [Fizzy](https://github.com/wasmx/fizzy).
=> [test] Add "invalid section id" tests

test/core/binary.wast
Reverts WebAssembly/spec#1230, should have gone to master.
=> Revert "[test] Add "invalid section id" tests"

document/core/syntax/instructions.rst
When you click on one of these links, you jump to the "Numeric
Instructions" section. But the definition of unop, binop, testop, relop,
and cvtop are in the "Conventions" section.
Move the label for these grouping non-terminals approriately, so
clicking on one of those definitions will go to where there are
defined.
=> Update label to syntax conventions

document/web-api/index.bs
The Response interface only exists in the Window and Worker scopes; these
methods are useless elsewhere.
=> [web-api] Only expose streaming methods where Response is exposed.

test/js-api/limits.any.js
This PR changes the tests in limits.any.js for memory size and table size to validate and compile modules that exceed implementation-defined limits. Only during instantiation and runtime, errors should be thrown.
In https://github.com/WebAssembly/spec/pull/1195 @Ms2ger requested that these tests get adjusted to to changes to the spec.
=> [tests] Adjust limits test to dynamic limits

test/core/binary.wast
Add tests for malformed import kind.
The following malformed values used:
04 - the lowest malformed value, but also used in exceptions extension,
05 - the lowest after exceptions extension,
80 - may detect reading import kind as LEB128 encoded value.
Related [wabt](https://github.com/WebAssembly/wabt) bug: https://github.com/WebAssembly/wabt/pull/1504, detected by fuzzing against [Fizzy](https://github.com/wasmx/fizzy)
=> [test] Add "malformed import kind" tests

document/core/exec/runtime.rst, document/core/util/macros.def, interpreter/text/parser.mly, test/core/func.wast
Fixes #1212. 
There is a complication here. In order to maintain the malformed/invalid distinction properly, we need to make sure that type definitions are only looked up during parsing when actually needed for computing symbolic indices. Otherwise, we'd turn some syntactically valid, fully desugared programs like the following:
```
(module (func (type 0) (local i32)))
```
into triggering a syntax error instead of a validation error (due to an undefined type index). My first naive attempt at a fix actually did that and regressed one test expectation from assert_invalid to assert_malformed, which e.g. means that it could not be converted to binary anymore.
Unfortunately, we generally don't know whether the type will be needed until we have seen the full function body and know whether it …
=> [interpreter] Fix symbolic local resolution with typeuse

test/core/binary.wast
The valid values are `00` and `01`. These tests checks if other values are reported as malformed.
The error messages reported by the interpreter are suspicious, so please double-check the tests and the interpreter implementation (I cannot ready OCaml).
This corresponds to [wabt](https://github.com/WebAssembly/wabt) bug https://github.com/WebAssembly/wabt/pull/1505, detected by fuzzing against [Fizzy](https://github.com/wasmx/fizzy).
=> [test] Add "malformed limits flag" tests

document/core/text/instructions.rst
Missing escapes were making the `f` in the instructions show up as a subscript.
=> Fix underscore for text format of trunc_sat instructions

test/core/binary.wast
Remove the code section in tests for malformed element section. Otherwise the code section id (0x0a) is taken as an element's table index what is a validation error.
This is similar to the previously reported issue: https://github.com/WebAssembly/spec/issues/1170.
=> [test] Correct tests for missing elements

test/core/data.wast
Related to the bug in WABT: https://github.com/WebAssembly/wabt/pull/1546,
found by [Fizzy](https://github.com/wasmx/fizzy) fuzzing.
=> [test] Add tests for data segment with memidx 1

test/core/binary-leb128.wast
In the binary-leb128.wast, change the alignment of an i32.store instruction from 3 (invalid) to 2 (the intention suggested by the comment).
=> [test] Correct i32.store alignment in a LEB128 test

test/core/exports.wast
This adds invalid cases with export section references nonexistent indices:
-  no function/global/table/memory is defined and export with index 0;
-  1 import is defined and export with index 1.
=> [test] Add more invalid cases with nonexistent exports

test/core/global.wast
This adds some cases with `global.get`/`global.set` with invalid index and a case with `global.set` for immutable imported global.
=> [test] Add invalid cases with globals access

test/core/local_get.wast, test/core/local_tee.wast
1. Fix cases with invalid index for `local.tee` - they looked to be copy-pasted from `local.get` tests without changing opcode.
2. Add `drop` instruction in the end of functions, otherwise tests might pass for the wrong reason - invalid index not caught, but invalid function return type reported.
3. Move some `type mismatch` tests of `local.tee` from `Invalid local index` section to `Invalid typing of access to parameters` section.
=> [test] Fix invalid index cases for local.tee and local.get

test/core/imports.wast
This adds cases to check imported global type matching - they try to instantiate providing global with incorrect value type or mutability.
=> [test] Add tests for validating imported globals

document/core/exec/instructions.rst
extend\F{\_}\sx isn't an operator, but extend_\sx is.
=> Fix usage of extend in t.load and t.loadN_sx

test/core/data.wast, test/core/elem.wast, test/core/global.wast
This adds cases for validation of
1. index of a global used in constant expression
2. immutability of a global used in constant expression
3. that only a single `i32.const` or `global.get` is allowed in constant expression.
=> [test] Add tests for validating constant expressions

document/README.md
cd-ed too deep into the tree, it doesn't not work with the next `make -C core` instruction.
=> Fix step-by-step guide instruction

interpreter/exec/int.ml
This makes it work for Rep.bitwidth < 32. Otherwise it will keep
checking all 32 bits and give the wrong result.
=> [interpreter] Make popcnt loop up to bitwidth

interpreter/script/js.ml
PR #1288 is the first use of global_i64, but the generated JS did not
yet define this global, which causes the JS test to fail to link.
=> Add global_i64 to js harness

test/core/imports.wast
While integrating [wasm3](https://github.com/wasm3/wasm3) into [fizzy](https://github.com/wasmx/fizzy)'s benchmarking suite, we found some issues with wasm3. Namely it did not make a distinction between imported and exported functions where the name matches. Since wasm3 passes the spec tests, I think such cases are not covered. The original test case can be seen at https://github.com/wasm3/wasm3/issues/143.
=> [test] Test cases with imports the same name as exports

test/core/exports.wast
This pull request adds a test to verify WebAssembly interpreters correctly handle the case where multiple exported functions share a single implementation. I've run into this problem when trying to use Libsodium with some Wasm interpreters. Libsodium exposes a number of different functions that wrap private constants, some of which are equal. These functions are all compiled down into the same WebAssembly function implementation with different exported names.
=> [test] Add tests for functions sharing same implementation

interpreter/binary/decode.ml, interpreter/binary/decode.mli, interpreter/binary/encode.ml, interpreter/binary/encode.mli, interpreter/syntax/types.ml, interpreter/valid/valid.ml
This adds functionality for en/decoding user defined custom sections to the En/Decode modules. Doesn't change the interpreter, but provides useful functionality for the Wasm lib build.
Also, rename `stack_type` to `result_type` to match spec.
The large diff in Encode.ml is misleading, since most of it just changed indentation.
=> [interpreter] Functionality for encoding custom sections

document/README.md, document/core/conf.py, document/core/util/bikeshed/conf.py, document/core/util/mathdef.py, document/core/util/mathdefbs.py
Since the build instructions suggest using pipenv, we should
consistently use pipenv to install the packages.
Also remove some warnings about unavailable static files.
Fix a Sphinx deprecation warning.
=> Small fixes in build instructions, fix warnings

.travis.yml, document/README.md, document/core/util/mathdef.py, document/core/util/mathdefbs.py
It comes with some nice fixes:
- genindex.html "abstract syntax" currently points to
"https://webassembly.github.io/spec/core/appendix/implementation.html#index-1",
which looks incorrect
The different files are:
$ diff -u -r _build/ _golden/ -q
Files _build/core/appendix/index-instructions.html and
_golden/core/appendix/index-instructions.html differ
Files _build/core/bikeshed/index.html and
_golden/core/bikeshed/index.html differ
Files _build/core/_download/WebAssembly.pdf and
_golden/core/_download/WebAssembly.pdf differ
Files _build/core/genindex.html and _golden/core/genindex.html differ
Files _build/core/objects.inv and _golden/core/objects.inv differ
Files _build/core/search.html and _golden/core/search.html differ
Files _build/core/searchindex.js and _golden/core/searchindex.js …
=> Upgrade Sphinx to 3.0.0

.travis.yml, document/README.md, document/core/index.bs, document/core/util/bikeshed/conf.py, document/core/util/bikeshed_fixup.py
The html_add_permalinks configuration was changed in 3.5
(https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_add_permalinks),
we don't want any permalink for the heading (that's the existing
behavior).
Fix up bikeshed_fixup.py, we were not correctly replacing the spurious
"navigation section" and also the Unicode reference.
Most of the changes in the output is:
- adding viewport meta tag (in Sphinx#7695, since 3.1.0)
- sorting order of css files in html
- upgrade mathjax to 2.7.7
=> Upgrade Sphinx to 3.5.2

document/core/make.bat
They were breaking the command block, so `make.bat help` output was:
> ./make.bat help
help       to see more options
=> Escape parentheses in echo line

proposals/bulk-memory-operations/Overview.md
=> Remove 'data passive' from bulk-memory examples

document/core/appendix/properties.rst, document/core/binary/modules.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst, document/core/static/custom.css
Visually separate formal rules from prose better by using a different background (light-grey) for display math.
Also fix #1299 and other minor layout improvements.
=> [spec] Layout improvements

test/core/imports.wast
I made this to check my understanding of the [external memory definition in the spec](https://webassembly.github.io/spec/core/exec/modules.html#xref-exec-runtime-syntax-externval-mathsf-mem-a): 
IIUC it requires imported memory to have `min` limit equal to it's currently allocated size, which means it can be updated after grow, and that has implications on matching this memory limits against import definition in another module.
The test basically creates a module with `(memory 1)`, grows it to 2 pages, then tries to import it into a module with `(memory 2)`.
Then repeats it another time for the memory that is both imported and exported.
(It [fails on WABT](https://github.com/WebAssembly/wabt/issues/1626).)
=> [test] Check that memory is exported/imported with correct min limit after grow

document/core/valid/instructions.rst
WebAssembly/reference-types#116 re-reversed the validation of br_table, but only did so in tests, interpreter, and the spec's algorithm appendix. It somehow missed the actual validation rule in the spec. This fixes that oversight.
=> [spec] Fix oversight in reversal of br_table validation

test/core/binary.wast
The same problem was already fixed once in https://github.com/WebAssembly/spec/pull/1261, but then was reintroduced in https://github.com/WebAssembly/spec/pull/1287.
=> [test] Fix alignment of i32.store instruction in binary test

document/js-api/index.bs
The links were accidentally changed to point to the reference-types fork
when it was merged in 7fa2f20a6df4cf1c114582c8cb60f5bfcdbf1be1.
=> [js-api] Fix links to the core specification.

document/js-api/index.bs
Names and affiliations are separated by a comma: https://tabatkins.github.io/bikeshed/#metadata-editor
=> Fix the Editor metadata format

document/core/syntax/modules.rst
=> [spec] fix markup for ref.func instruction

test/core/br_table.wast, test/core/select.wast, test/core/unreachability.wast, test/core/unreached-invalid.wast, test/core/unreached-valid.wast
This PR factors out tests that deal with validating unreachable code in the presence of the bottom type. Specifically, both `select` and `br_table` have tricky corner cases that probably deserve their own file.
The motivation for this PR is merely to factor out these tricky corner cases into their own test file in anticipation of any more corner cases that are found or any future changes to how unreachable code is validated. This makes it easy to pinpoint the changes introduced and to diagnose the problem in implementations.
=> Factor unreachability tests out of select and br_table

document/js-api/index.bs
Although it was un-exported from HTML recently, this is one of the very few specs which has legitimate reason to link to it.
=> [js-api] Fix link to HTML.

document/core/binary/instructions.rst, document/core/binary/types.rst, document/core/exec/instructions.rst, document/core/syntax/instructions.rst, document/core/text/instructions.rst, document/core/util/macros.def, document/core/valid/instructions.rst
Discovered while working on WebAssembly/function-references#49.
=> [spec] Fix a bunch of minor issues

.github/workflows/main.yml
This PR addresses some comments in https://github.com/WebAssembly/spec/issues/1342#issuecomment-881284494 about the recently merged CI PR #1344.
* Uses pip to install the latest bikeshed to use that for JS/Web API docs (instead of a pinned older version)
* Only publish the `.html`, not the `.bs` or `Makefile`
=> [CI] Adjust JS/Web API build to use latest bikeshed

document/core/exec/instructions.rst
Fix #1357.
I checked all other bulk ops, but didn't find any other typos of this kind.
=> [spec] Fix variable name typos

test/js-api/table/get-set.any.js
The spec allows a missing `value` parameter in `WebAssembly.Table.set`, see https://webassembly.github.io/spec/js-api/index.html#dom-table-set.  There is a test, however, that `WebAssembly.Table.set` throws if there is no `value` parameter. This PR deletes that test.
=> Remove outdated table test

.github/workflows/mirror.yml
I created [main branch](https://github.com/WebAssembly/spec/tree/main) on the remote so this should work now.
I don't expect any downstream (forks/proposals) to have issues, since master will still exist. This mirroring will mirror any changes on main to master, so it will be kept up to date.
Follow-up to this will be to update places like https://github.com/WebAssembly/proposals/blob/master/howto.md to refer to main.
=> Add action to mirror main to master

test/core/binary.wast
=> [test] Fix binary test

.github/workflows/main.yml
Default branch is now main, so all the PRs are based on main, which
means the actions aren't currently triggered, since they only run on
push to master. Update it to main.
Since we have the main->master mirror, we should still be testing, but
it is a bit delayed (only after the mirror I think, and not on the PR).
=> Use main in github workflow

.github/workflows/main.yml, document/README.md, document/core/conf.py, document/core/util/bikeshed/conf.py
Changes:
https://www.sphinx-doc.org/en/master/changes.html#release-4-0-0-released-may-09-2021
Things to note:
- docutils updated to 0.17
https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-17-2021-04-03
the big change here is to use semantic elements, `<div class="section">`
is now `<section>`, I see this a whole bunch when I diff the output HTML.
- supposedly some html themes break due to the docutils change, probably
due to divs not matching, I don't see any visible breakage, so it should
be fine
- mathjax 3
https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html it's
faster to render, we need to tweak our configuration a bit, to
camelCase, so updated it in conf.py
I diffed the output html, some differences I noted:
- div -> section as noted above
- a new meta tag for …
=> Upgrade to Sphinx 4.0.0

document/core/index.rst, document/core/util/mathjax2katex.py
This allows us to drop some manual links removal in mathjax2katex.py.
=> Only include ref links to index in multi-page html

document/core/conf.py
'%F' is not a supported format, see
https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/util/i18n.py#L133,
it is also not supported in Python's strftime/strptime
https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior.
It is however supported in strftime
(https://man7.org/linux/man-pages/man3/strftime.3.html) and defined to
be "%Y-%m-%d", which is supported by sphinx.
=> Fix html_last_updated_fmt

interpreter/exec/int.ml
The meaning of `!=` is [implementation-dependent](https://www.ocaml.org/api/Stdlib.html) in OCaml. This seems undesirable for a reference interpreter.
This PR switches to to `<>` which checks for structural non-equality rather than physical non-equlity.
=> Remove use of physical equality on characters

test/core/binary.wast
Inspired by this downstream test in wabt: https://github.com/WebAssembly/wabt/pull/1775
Fixes: #1404
=> Add tests for functions without end marker. NFC

document/core/text/modules.rst
While implementing this specification, I became confused as note clarifying the expansion grammar was confusing me.
"The latter abbreviation can be applied repeatedly, with “…” containing another import or export."
^^ seems to hint that you can do (export) (import) (export) (import) resulting in multiple imports that won't work as there can be at most one and really only exports can repeat.
This changes the text to hopefully prevent future folks from reaching the same misconclusion.
Fixes #1418
=> Clarifies the note on text format export abbreviation expansion to reflect impact

interpreter/binary/decode.ml, test/core/binary.wast, test/core/custom.wast
=> [test] Fix section size in binary test

test/core/run.py
This will return early right after generating JS from the wast test
files. It will not attempt to run the tests, or do the round trip
conversion from wasm <-> wast.
This is convenient for proposals to add tests without having to
update the reference interpreter with implementation, and generate those
tests to JS to run in other Wasm engines.
Fixes #1430.
=> Add --generate-js-only flag to test runner

document/core/exec/modules.rst
The current spec (in 4.5.4 Instantiation) asserts that active elem segments may only reference table #0. (The reference-types proposal removed this limitation from 2.5.7 Element Segments, but left the corresponding assertion in 4.5.4 Instantiation. I think this was probably unintended and the assertion is vestigial?)
This PR removes the assertion and allows active elem segments to reference any tableidx.
=> [spec] Fix single-table limitation in module instantiation

document/core/exec/instructions.rst
The table.set instruction was missing its immediate `x` in the execution spec heading.
=> [spec] exec/instructions.rst: fix missing immediate on table.set

proposals/multi-value/Overview.md
This fixes compilation errors in examples. It also changes case format of phis to PHIs so that people don't first wonder if they are reading a typo.
=> multi-value: fixes compilation errors in examples

document/core/appendix/changes.rst, document/core/conf.py, document/core/index.bs, document/js-api/index.bs, document/web-api/index.bs, interpreter/main/main.ml
At yesterday's WG meeting, we decided to make a new release, now switching to the Evergreen model. For administrative and technical reasons having to do with W3C procedure, we decided to bump the release number to 2.
From now on, the standard will iterate at *version* 2 from the W3C's official perspective. We use minor *release* numbers internally to distinguish different iterations.
(@ericprud, I hope I understood correctly that the Bikeshed "level" also needed to be bumped to 2.)
=> [spec] Bump release to 2

proposals/bulk-memory-operations/Overview.md
Lost some time not noticing this. While it is possible others will guess sooner than I did
by function name and it isn't exported that they should add it as a start function, better
to be explicit I think.
=> Adds missing start from overview example

document/core/exec/runtime.rst
I think this paragraph was meaning to say **or** i.e.
`number types | vectors | reference types`
=> Replace of with or

test/core/unreached-valid.wast
This PR adds an overlooked assertion for a valid case of unreachable code is actually callable and traps.
=> Add assert_trap for unreached valid case

document/core/binary/modules.rst, test/core/binary.wast
Change the encoding of data/element segment tags to be a full LEB u32 instead of a single byte. This matches test suite, reference interpreter, and major engines like V8, JSC(*), Spidermonkey, and Wasmtime. It also reinstantiates backwards compatibility with the Wasm 1.0 format.
Fixes #1439.
(*) With the one exception that JSC [apparently](https://github.com/WebAssembly/spec/issues/1439#issuecomment-1088922572) requires a single byte for element segments but not data segments, an inconsistency that seems more like accident than intent.
=> [spec] Fix binary format of data/elem tags to allow LEB

wasm-specs.bib
Dear WebAssembly maintainers and developers,
I propose a small contribution by updating the BibTeX file with the Wasm specs 2.0.
I removed the PDF link (in note) for the Wasm specs 1.0 since this URL is constantly updated with the latest specs. Feel free to propose another URL that would reference the PDF for the first iteration of the specs (if needed).
Do not hesitate to ask for other changes to the BibTeX entries in case you see other enhancements.
Cheers,
Jämes
=> Update latex .bib file for citing webassembly specs 2.0

document/core/appendix/embedding.rst, document/core/appendix/properties.rst, document/core/binary/modules.rst, document/core/exec/conventions.rst, document/core/exec/instructions.rst, document/core/exec/modules.rst, document/core/exec/numerics.rst, document/core/intro/overview.rst, document/core/syntax/conventions.rst, document/core/syntax/instructions.rst, document/core/text/conventions.rst, document/core/text/modules.rst, document/core/valid/conventions.rst, document/core/valid/instructions.rst, document/core/valid/modules.rst, document/js-api/index.bs, document/web-api/index.bs
=> Fix mistakes

document/js-api/index.bs
At the moment the spec requires a `LinkError` to be thrown when the `WebAssembly.Global` constructor is called for type `v128`. This was introduced in https://github.com/WebAssembly/simd/pull/360, but according to the PR description, actually a `TypeError` should be thrown. The PR refers to https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#javascript-api-and-simd-values, and there a `TypeError` is required.
=> TypeError for Global constructor with v128

interpreter/binary/decode.ml, interpreter/binary/encode.ml
Fixes #1485.
While there, rename numeric en/decoding functions to match spec grammar.
@msprotz, PTAL.
=> [interpreter] Produce error messages in encoder

interpreter/exec/eval.ml, interpreter/exec/ixx.ml, interpreter/runtime/data.ml, interpreter/runtime/data.mli, interpreter/runtime/elem.ml, interpreter/runtime/elem.mli, interpreter/runtime/instance.ml
In order to enable replacing them with a different representation.
@vapourismo, PTAL.
=> [interpreter] Factor data and element segments into modules

document/core/exec/modules.rst
Clarify that module initialization can trap when executing the init instruction corresponding to an active segment, in addition to the start function.
=> exec/modules.rst: clarify module initialization trapping

document/core/appendix/algorithm.rst
Address #1495.
Ended up not changing the algorithm but rather explaining the invariant. We could add an explicit assertion to the `unreachable` function, but that wouldn't add anything, so I decided against it.
=> [spec] Add note about control stack invariant to algorithm

document/core/text/lexical.rst, interpreter/text/lexer.mll, test/core/tokens.wast
As discussed at the last meeting, this disallows omission of spacing around string tokens and adds a tokenisation test. Supersedes #1490.
=> [spec] Tweak tokenisation for text format

document/core/valid/instructions.rst
I believe the inference rule now matches the prose.
=> Fix table.copy validation typo

document/core/intro/overview.rst, document/core/syntax/modules.rst, document/core/valid/instructions.rst, document/core/valid/types.rst
I properly read the spec and found some minor suggestions I wanted to provide for your consideration.
=> Minor copy edit suggestions

test/core/start.wast
The documentation states that the start function is validated before
it states that imports are validated. This does not imply a required
ordering to the validation process but some implementations may order
order their validation implementation as stated regardless. If the
start function is validated before the imports, while assuming
the imports are valid without first checking if the imports are valid
then this may trigger a bug.
=> Test validation when using start with invalid imported function

test/core/imports.wast
The test suite was missing tests that check if the validator reject imports with invalid memory or table types.
=> Test invalid memory / table import types

document/core/exec/instructions.rst
This is how the interpreter implemented it, which should be in sync. It's the simpler formulation, so changing the spec instead of the interpreter.
=> [spec] Simplify exec rule for if

document/core/binary/instructions.rst
Remove the extra newline and vertical bar after the encoding for the `i64x2.ge_s` instruction.  This matches the formatting for the rest of the instruction groups.
=> Correct formatting error in instructions.rst

document/core/appendix/index-rules.rst, document/core/appendix/properties.rst
The appendix was not updated for the bulk op extension, so missed the addition of elem and data components to the context.
=> [spec] Fix typing rule for module instances

document/core/valid/instructions.rst
Fix editorial issue that came up in #1521.
=> [spec] Correct use of opdtype and stacktype

document/core/appendix/gen-index-instructions.py, document/core/appendix/index-instructions.rst
=> [spec] Add note to instruction index

document/core/valid/instructions.rst, document/core/valid/modules.rst, interpreter/valid/valid.ml, test/core/data.wast, test/core/elem.wast, test/core/global.wast
Fix #1522:
* Use restricted context for typing data/elem/memory/table.
* Add corresponding tests.
=> [spec/test] Fix scoping of non-imported globals

document/core/exec/modules.rst
In the other definitions for allocations type is defined as the type of the thing that is to be allocated
=> The variable t looks like it is not defined in the exaplanation text.

document/js-api/index.bs, document/web-api/index.bs
=> [js-api][web-api] Editorial: Fix some minor issues.

test/meta/generate_memory_copy.js, test/meta/generate_memory_fill.js, test/meta/generate_memory_init.js, test/meta/generate_table_copy.js, test/meta/generate_table_init.js
The error strings in the core testsuite were cleaned up in https://github.com/WebAssembly/reference-types/pull/117 (see https://github.com/WebAssembly/reference-types/issues/113), but some of the tests (for table/memory init and copy, and memory_fill) are auto-generated by upstream JS that wasn't edited at the same time.
The PR syncs the JS scripts so that they will generate the current tests.
=> test/meta/generate_*.js: sync upstream JS with tests

test/core/elem.wast
=> elem.wast: test segment/table mismatch and active externref segment

interpreter/text/parser.mly
This patch tidies up the `parser.mly` module by removing two instances of `%prec` that were never useful. More importantly, this patch also removes duplicated token declarations as `menhir` considers such an error in debug mode. Consequently, it is now possible to debug the grammar using `menhir --explain` or similar.
=> [interpreter] Remove duplicated token declarations.

interpreter/script/js.ml
https://github.com/WebAssembly/spec/commit/82a613da5ea18515bf6f16593b8f7b608f47380f added `print_i64` to the standalone test files, but not to the ones generated by the spec interpreter.
=> Add `print_i64` to generated spec tests

document/core/text/lexical.rst
Rather than describing keyword tokens as always being defined implicitly by terminal symbols in syntactic productions, describe them as being defined implicitly or explicitly. This accounts for the explicit definitions of `offset` and `align` phrases, which are lexically keywords, later in the chapter.
Fixes #1552.
=> [spec] Allow explicit keyword definitions

document/js-api/index.bs
Right now the text for the "v128" type in the [JS API doc](https://webassembly.github.io/spec/js-api/index.html) links to https://webassembly.github.io/spec/core/syntax/types.html#syntax-numtype, but the type is not actually defined there.
This minor PR makes it link to https://webassembly.github.io/spec/core/syntax/types.html#vector-types instead.
=> [js-api] editorial: adjust link for v128 type

document/core/appendix/properties.rst, document/core/exec/instructions.rst, document/core/exec/runtime.rst, document/core/valid/instructions.rst
This fixes a bunch of minor oversights and notational inconsistencies that I discovered while writing up a rule summary. Most of them occur in the execution rules for bulk instructions.
=> [spec] Fix minor errors and inconsistencies

interpreter/text/parser.mly, test/core/call_indirect.wast, test/core/select.wast
=> [interpreter] Refactor parser to handle select & call_indirect correctly

test/core/elem.wast
This change makes the test detect this bug in toywasm. https://github.com/yamt/toywasm/commit/89465d57a8ad07a2e159711c92d3625bf66c41c7
(without this change, all tests were passing even with the bug.)
Note: toywasm CI uses tests converted with wast2json.
Note: wast2json doesn't use exprs unless the element contains exprs other than ref.func.
https://github.com/WebAssembly/wabt/blob/712bb5c908c35de7e4878463bb26ca0c89dac479/src/ir.cc#L680-L682
=> [test] elem.wast: force to use exprs in a element

document/core/exec/instructions.rst
it should be i8x16.swizzle and shuffle, not v128.
=> Fix typos in SIMD exec/instructions

test/core/table_fill.wast, test/core/table_get.wast, test/core/table_grow.wast, test/core/table_set.wast, test/core/table_size.wast
These weren't being exercised in the testsuite, and some parsers (including WABT) can't currently parse them.
(The abbreviations for table.copy and table.init are already tested in bulk.wast.)
=> Test the abbreviated forms of table.{get,set,size,grow,fill}

document/core/text/instructions.rst
=> [spec] Fix label shadowing

document/core/text/instructions.rst
This removes the unnecessary vertical bar.
=> [spec] Fix typo

document/core/exec/modules.rst
Other steps are written in one line, but this step contains newline.
This removes the newline for consistency.
=> [spec] Remove inconsistent newline

document/core/static/custom.css
Without scrolls ([text/modules#Abbreviations](https://webassembly.github.io/spec/core/text/modules.html#id7)):
With scrolls:
=> [spec] Show scrolls for overflow math blocks

document/core/exec/instructions.rst
=> Remove stray `x` indexes from `memory.fill` and `memory.init` descriptions

document/core/syntax/conventions.rst
Addresses discussion point [here](https://github.com/WebAssembly/spec/issues/726#issuecomment-1431227194).
=> [spec] Clarify in conventions that atoms can be symbolic

.github/workflows/main.yml, interpreter/Makefile, test/core/linking.wast
Adds a simple test for ex/importing a global of type v128.
@ajklein, @jakobkummerow, this makes V8's InstanceBuilder crash, presumably because v128 isn't handled [here](https://github.com/v8/v8/blob/main/src/wasm/module-instantiate.cc#L1446) (tested with node 18.14.0, the CI failure is caused by that as well).
=> [test] Import v128 global

document/js-api/index.bs
=> [js-api] Try to clarify NaN/infinity handling.

document/web-api/index.bs
=> [web-api] Correct MIME type check.

document/js-api/index.bs
On JSC, some compilation work takes place the first time that a
Module is instantiated. If the module is instantiated in an
asynchronous way, the work happens off the main thread. This patch
loosens the specification of WebAssembly module instantiation
to permit this specific type of delay.
Based on skimming the code (but not running tests), I believe that
the new specification matches 3/4 of the implementations I examined.
The one which might not fit is V8, which defers reading properties
of the import object to a microtask queue item at the beginning
of WebAssembly.instantiate(Module), unlike the others, which read it
synchronously.
The previous specification didn't match any implementations, as it
specified to queue an HTML task at the beginning of the
WebAssembly.instantiate(Module) …
=> [spec] Normative: Permit work in parallel during instantiation

.github/workflows/main.yml, README.md
Exception handling repo's 'build-core-spec' CI started failing suddenly today (2/17/2023) for no apparent reason and is still failing even after merging with the upstream spec:
https://github.com/WebAssembly/exception-handling/actions/runs/4208125522/jobs/7303774774
This is a test PR to see if the spec repo has the same issue. Will close this after the CI testing. Do not merge.
=> [ci] Pin nodejs version to avoid fetching failures

document/core/exec/instructions.rst
This rule was probably copied from the (very similar) memory.grow rule when it was introduced by #1287 in c3d5cbc1f7c6b166b7a312adc4efdb7e34746b3d. While memory.grow doesn’t have an initialization value, table.grow does.
=> [spec] Add missing initialization value to table.grow reduction rule

test/js-api/wasm-module-builder.js
The section name has changed to the tag section a few years ago. This adds the corresponding changes added in
WebAssembly/exception-handling#252 and
WebAssembly/exception-handling#256.
=> [test] Exception -> Tag in wasm-module-builder.js

.github/workflows/main.yml, test/core/binary.wast
Current `assert_malformed` invalid section ID tests are passing, meaning they fail to validate, but not because of invalid section IDs. https://github.com/WebAssembly/spec/blob/721dd6ce2cf53028133bd2ceeea9b0655570c641/test/core/binary.wast#L47-L52
They still fail to validate after replacing those invalid section IDs with valid ones, such as `01` or `02`. For example, Look at the (malformed) module in the first line, which says `0d` (13) is an invalid section ID:
```wast
(module binary "\00asm" "\01\00\00\00" "\0d\00")
```
Actually now all major web browsers and Node have implemented EH and expose it by default (= without a flag). So that should be `0e` now, even before we merge the EH proposal.
But anyway, this module fails to validate not because `0d` is an invalid ID. If you replace it …
=> [test] Fix invalid section ID tests

document/core/exec/instructions.rst
This pull requests fix typos in the execution of some of the vector instructions,
by appending missing period or adding the missing `:math:` block to some of the steps.
=> [spec] Fix typo in execution of vector instructions

document/core/exec/instructions.rst
This pull request will
1. Fix some typos regarding periods.
2. Append the step `Let F be the current frame <syntax-frame>.`, when needed for `expand_F`. (block, loop-block)
3. Remove use of `F` in formal notation if unnecessary. (if-block)
=> [spec] Fix execution of control instructions, regarding current frame

document/js-api/index.bs
WebRef has recently added definitions for ECMAScript, which means most of the explicit anchor definitions are no longer needed. Also, some abstract operations had their names changed.
This change should be entirely editorial.
=> [js-api] Remove some anchor definitions

document/core/exec/modules.rst
A closing parenthesis seems to be missing for the condition of module instantiation.
So this pull request simply adds a closing parenthesis for it.
=> [spec] Fix typo in module instantiation of execution

document/core/valid/modules.rst
The link for `The expression ei must be constant.` points to the text for `t.const` instructions, not to the text for constant expressions.
=> [spec] Use the correct link to in element sections

test/core/elem.wast
=> [test] Add test for table elems initialized by imported global funcref

document/js-api/index.bs
Just add thousand separators for more human-friendly parsing of the limits.
=> [js-api] Editorial: add grouping separators to limit values

test/core/binary.wast
WABT was not catching this case (https://github.com/WebAssembly/wabt/pull/2218).
=> [test] Add test for init expr with missing end marker

test/js-api/limits.any.js
The limits test did not test the maximum supported module size of 1GB yet. This PR adds tests which create modules consisting of a single custom section. The first test checks if a module of size 1GB is allowed, the second test checks that a module of size 1GB + 1 byte gets rejected.
=> Add test for the module size limit

test/core/binary.wast
With memory64, memory offsets will be decoded as u64. An engine implementing this will fail tests that test that we reject such module. Thus remove those tests from the main spec repo now; they should be added back in the memory64 repo, but changed to `assert_trap` tests.
=> [test] Remove malformed tests that become valid with memory64

test/core/binary-leb128.wast
This merges part of WebAssembly/memory64#14 to make the tests fail both before and after memory64. This allows engines to enable memory64 without failing spec tests.
=> Make binary-leb128 test memory64-ready

test/js-api/limits.any.js
Allocating a 1GB Uint8Array can fail. In particular, it will always fail on 32-bit systems in V8, where the maximum size of a TypedArray is 2^30-1, thus 1 byte too little.
=> Allow test for module size limit to fail

document/core/text/modules.rst
=> [spec] Include correct reftype in inline element segment abbreviations

interpreter/exec/eval_num.ml, interpreter/exec/v128.ml, interpreter/runtime/data.ml, interpreter/runtime/elem.ml, interpreter/runtime/memory.ml, interpreter/runtime/table.ml, interpreter/util/lib.ml
This allows to compile with -unsafe without getting a segfault or a random value.
There's something I don't understand in `interpreter/runtime/table.ml` and I left a comment there. I believe we should simply remove the `Invalid_argument` case.
It's a little bit unrelated but I also replaced all `raise (Invalid_argument s);` by `invalid_arg s;` (so that it's easier to grep for `Invalid_arg` to check if we're catching it).
Also unrelated, but it seems the `Array32.make` function in `interpreter/util/lib.ml` is wrong. IIUC it should check for `Sys.max_array_length` instead of `Int64.of_int max_int` (and `Sys.max_floatarray_length` if the array is made of floats, which is `Sys.max_array length / 2`).
=> add explicit bounds checks and do not catch Invalid_argument anymore

document/core/appendix/properties.rst, document/core/exec/instructions.rst
The execution section for `elem.drop` was missing the `type` field of element instances. In addition, the heading of the Element Instances section in the Soundness appendix was also missing the type. I have added the type to both places.
This is my first contribution to the spec repo, so apologies if I got any conventions wrong.
Would close #1663 if it wasn't already closed for some reason.
=> Add type to elem.drop and element segment store soundness

test/core/float_literals.wast
Add `assert_malformed` tests for `f32.const nan:0x800000` and `f64.const nan:0x10000000000000`, which are malformed since the payload values are outside the range supported by the types.
=> [test] Add tests for out-of-range NaN payloads

document/core/binary/modules.rst
depended → dependent
Alternative: "whose structure depends on"
=> Fix typo in § 5.5.2 Modules

test/core/if.wast
Check that the condition must be a sequence of folded (as opposed to unfolded)
instructions, but also check that having zero or multiple folded instructions is
allowed.
=> [test] Test that atypical folded if conditions are parsed correctly

interpreter/exec/eval.ml
Change the interpreter implementation of backward copying in the evaluation of
memory.copy and table.copy to match the implementation given in the spec. This
does not change any behavior.
=> [interpreter] Update {memory,table}.copy to match spec text

.github/workflows/ci-interpreter.yml
It ought to not be needed after https://github.com/WebAssembly/spec/pull/1665.
=> Don't install ocamlbuild in CI

document/core/exec/modules.rst
Related to #1690.
This PR adds a new step "pop the dummy frame" to [Invocacation](https://webassembly.github.io/spec/core/exec/modules.html#invocation)
=> [spec] Add a new step to Invocation

document/core/exec/numerics.rst
=> [spec] Fix definition of iextend

document/core/exec/runtime.rst, document/core/util/macros.def
Fix #1693 by separating the syntactic categories of frames and of their state.
=> [spec] Cleaner definition of frames

document/core/appendix/index-instructions.py, document/core/exec/instructions.rst, document/core/exec/numerics.rst, document/core/util/macros.def
I noticed that the definition for mapping numeric ops over lanes was incorrect. This should fix it, and also improves some of the cross-referencing for numeric ops.
@ngzhian, can you take a look?
=> [spec] Fix definition of lane ops + better xrefs

interpreter/dune, interpreter/dune-project, interpreter/jslib/wast.ml, interpreter/script/js.ml, interpreter/script/run.ml, interpreter/text/arrange.ml, interpreter/text/parse.ml, interpreter/text/parse.mli, interpreter/text/parser.mly, interpreter/wasm.opam
Hi @rossberg,
As discussed in [WebAssembly/gc#474](https://github.com/WebAssembly/gc/pull/474), I switched to Menhir.
In a second commit I demonstrate some of the facilities offered by Menhir. There are plenty others we could use to remove some code. But I already did this in Owi and I'm not feeling like rewriting a whole parser for the second time right now. :-)
=> switch to menhir

document/core/valid/instructions.rst
=> [spec] Add missing length condition to br_table prose

document/core/exec/instructions.rst
There seems to be some typos in shape.all_true instruction and txN.bitmask execution.
The parameter is labeled as $c_1$, but the some of the ones used are just labeled $c$.
This pull request changes all the incorrect $c$ to $c_1$.
=> [spec] Fix typo in shape.all_true and txN.bitmask instruction execution

test/core/binary.wast
Current implementation fails on streaming validation due to interpreting `0x020x0b` as block with type 11 which doesn't exist; so add enough types such that `0x0b` resolves to a valid one, thereby passing validation and erroring at the expected state.
This was previously reported in https://github.com/WebAssembly/spec/issues/1355 but never fixed, and I've just discovered it for myself.
Suggestions for making this more realistic or safe welcome! I'm a bit concerned about adding so many duplicate types in here but I don't believe that's illegal according to spec. My first pass at this changed the first `0x0b` to an `0x00` but that breaks the realism a bit too much since you need the 3 breaks and the wild `0x00` makes no sense. The test is trying to get at the br_table having a missing byte.
=> test(binary.wast): adjust br_table length test to work with streaming validation

document/core/exec/instructions.rst
At step 11 of the definition of extmul (below image), there is an expression $`\text{imul}_{t_2 \times N}(k_1^*, k_2^*)`$.
I guess it should be $`\text{imul}_{|t_2|} (k_1^*, k_2^*)`$.
The underscored argument of $`\text{imul}`$, which is $`t_2 \times N`$ is typed wrong. From the definition of $`\text{imul}`$, its argument should be an integer.
Here, from line 12, $`k^*`$ should be a sequence of length $`N`$ with its elements typed $`t_2`$. So I think the argument should be $`|t_2|`$.
Same problem occurs in the definition of extadd (below image).
I think the expression $`\text{iadd}_N(j_1, j_2)^*`$ at step 6 should be $`\text{iadd}_{|t_2|} (j_1, j_2)^*`$ instead, and fixed the document.
Another solution (which I'm not so sure of) could be using the lane-wise applying notation.
With this …
=> [spec] Fix extmul & extadd execution

interpreter/dune-project, interpreter/wasm.opam
Add depends to `dune-project` so that dependencies can be installed by calling `opam install . --deps-only --with-doc --with-test` and then build the interpreter from source :)
=> [interpreter]: Add depends to dune-project

interpreter/script/js.ml, test/core/imports.wast, test/harness/async_index.js, test/harness/sync_index.js
In the file `interpreter/host/spectest.ml`, the global float values for F32 and F64 are 666.6,
but in the file `interpreter/script/js.ml`, the float values are 666.
This pull request changes the float values 666 in `js.ml` into 666.6.
Also, this indicates that the test suite did not contain the test for checking the value of imported global values,
and this pull request also adds new tests in `imports.wast` test file.
=> [interpreter/test] Fix inconsistent use of float values in `spectest`

document/core/exec/instructions.rst
The order of the arguments in the instruction shape.replace_lane is different to the order of the pop in the execution.
The execution pops t1.const c1 first even though it is presented as the left-most argument. 
This pull request changes the order of the arguments to match the pop operations and the subscripts of variables accordingly.
=> [spec] Fix argument order in shape.replace_lane instruction of execution

test/core/float_literals.wast
Tests for parsing of float literals that are integers. Related to [this wabt bug](https://github.com/WebAssembly/wabt/issues/2388).
=> [test] Tests for period-less float literals

test/core/run.py
After this change I can run the following commands from the top level of the repository:
```
$ make -C interpreter/
$ test/core/run.py
```
Without this change `run.py` looks for wasm in my current directory which will fail when run from anywhere except the `interpreter` directory and forces me to run `test/core/run.py --wasm interpreter/wasm`.
=> run.py: Better default for wasm executable

test/core/elem.wast
This failure case could be equally valid as "type mismatch" if a validator is validating one opcode at a time rather than consuming them all then validating the return type.
It wants a `ref.func` but the first opcode it finds is an `i32.const` so a streaming validator should be able to error on the first opcode rather than wait for more to decide that it's not a constant expression.
I can't think of an alternative to replace this with, so I'm suggesting this case is unnecessary and too ambiguous.
=> Remove failure case with ambiguous error options

.github/workflows/ci-spec.yml, .github/workflows/w3c-publish.yml
This change splits the publish-to-W3C-TR job out into its own separate workflow, and only runs that workflow for pushes to the main branch — but not for pushes to pull-request branches.
=> [CI] Publish to W3C only on push to main

document/core/valid/modules.rst
Under the current module typing rules, if a module defines any module elem/data segment with an active mode, then it cannot be well-typed: this is because the definition requires each elem/data to be well-typed under the C' context, but no tables and memories exist there.
This proposed change fixes this issue by allowing the module elem and data segments to access the full tables and memories accessible in the module.
=> [spec] Fixing module typing for active elem/data segments

document/js-api/index.bs
=> [js-api] Integrate with the ResizableArrayBuffer proposal

document/core/Makefile, document/core/text/lexical.rst, document/core/text/modules.rst, document/core/util/check_macros.sh, document/core/util/macros.def
Since neither Sphinx nor MathJax provide any diagnostics for it, this PR adds a simple script to check that all xrefs in the macros.def file are well-defined — and fixes various definitions on the way.
=> [spec] Check and fix cross-references

test/meta/Makefile
Honestly I'm not sure it worth maintaining the complexity of supporting anything but node here.
=> Use `node` over `spidermonkey` by default in test/meta/Makefile. NFC

interpreter/binary/decode.ml, test/core/align.wast
let's see what CI says about these...
closes #1749
=> Add tests for alignment overflow

test/core/memory.wast
=> Test that exporting random globals does not change memory semantics

document/core/binary/modules.rst
In the binary format, when treating the number distinguishing different kinds of element sections as a bitfield, the first bit distinguishes active segements from passive/declarative segments.
The previous phrasing used "indicate" to mean that a 1 bit signifies "passive or declarative", however it is easy to misread this as passive and declarative referring to the two possible values of the bit instead.
This change modifies the description of Bit 0 to make it clearer that it is differentiating active from passive or declarative, not passive from declarative, by using the "distinguishes ... from ..." language used in describing bit 1.
=> [spec] Clarify binary element bitfield meaning.

document/core/valid/instructions.rst
The latex version of validation for vector load/store_lane currently use strict equalities for alignment bounds instead of the intended `\leq`.
=> [spec] Small typo in validation of vector load/store_lane

document/util/htmldiff.pl, proposals/bulk-memory-operations/Overview.md, proposals/multi-value/Overview.md, proposals/reference-types/Overview.md, proposals/simd/SIMD.md, test/core/float_exprs.wast, test/core/simd/simd_load.wast, test/core/simd/simd_store.wast, test/core/utf8-custom-section-id.wast, test/core/utf8-import-field.wast, test/core/utf8-import-module.wast
This PR fixes a couple typos (as well as a citation misspelling 👀) that got flagged by automated checks on my own fork.
=> chore: fix typos

interpreter/text/arrange.ml
According to how names are parsed in `text/lexer.mll`, it looks like some escaping was missing in the text-format printing ?
=> add missing cases in name printing escaping

test/core/binary.wast
Only the start section had a test assuring its uniqueness. Cases in which there were two or more of the other sections weren't failing when implementing LibWasm for the Ladybird browser.
I'm not sure if these test cases are totally needed, but LibWasm's `Module` type used to have an interesting way to represent sections, and these cases slipped through... so feel free to close this PR if it's deemed unnecessary.
=> [test] Add tests checking that multiple sections aren't supported

document/core/static/custom.css
This is to allow that the documents of the specification display well on a narrow viewport. On viewports 100px or more wide, it does nothing, and, on viewports less than 1000px wide, it shrinks the document to the width of the viewport.
The issue is discussed here: #1774
=> Unset the width of documents in CSS

document/LICENSE
It's just a link to the W3C's license.
Fixes #1758
=> Create LICENSE file

test/core/binary.wast
As far as I know, there are no tests that suggest the correct order of sections. Binary modules with out-of-order sections are not failing in the Ladybird WebAssembly implementation, LibWasm.
=> [test] Add negative test for invalid section ordering

test/core/float_exprs.wast
In addition to testing `demote(x-promote(y))`, also test `demote(promote(y) - x)`. And test similar mixed-type cases for multiply and divide.
=> [test] Add a few more mixed-type floating-point expression testcases.

test/core/float_misc.wast
Add a sqrt test for values around ¼, where `sqrt(x) - x` is greatest.
And add a few more sqrt test values based on divergences in sqrt implementations found in the wild.
=> Add more tests for `sqrt`.

.github/workflows/w3c-publish.yml, document/Makefile, document/core/Makefile, document/js-api/Makefile, document/web-api/Makefile
This is derived from #1764 but does not actually change the publication status by default locally or on CI (ED is the default, and the w3c echidna publication action overrides it to WD).
It also includes a fix to the echidna Makefile rules to exit with an error in case an underlying step returns an error.
=> Update Makefiles for easier generation of different document status

.github/workflows/w3c-publish.yml
When manually dispatching workflows, inputs can be collected from the dispatching user and passed to the workflow. Use this feature to allow manually setting the W3C_STATE of the document. This will let us publish CR drafts on every push (once we update the default state from WD) and CR snapshots on demand.
=> Add input for workflow dispatch for W3C publish workflow

test/core/imports.wast, test/core/memory_grow.wast, test/core/table_grow.wast
No previous tests check that `table.grow` grows the table instance's type. This was found when implementing LibWasm for the Ladybird browser.
=> [test] Add tests ensuring table type is grown in `table.grow`

document/core/Makefile, document/js-api/Makefile, document/web-api/Makefile
This is the record of the decision to advance the current spec to CR
=> Update DECISION_URL for Wasm 2.0 CR advancement

document/core/Makefile, document/deadline.py, document/js-api/Makefile, document/web-api/Makefile
The Makefiles now generate a date 30 days in the future, and pass this date to bikeshed as 
the standard 'Deadline' metadata.
Along with https://github.com/speced/bikeshed-boilerplate/pull/98, this causes the document
status section to generate with a transition deadline always 30 from the generation time.
=> Generate deadline and pass to bikeshed as metadata

interpreter/README.md, interpreter/script/js.ml, interpreter/script/run.ml, interpreter/script/script.ml, interpreter/text/arrange.ml, interpreter/text/lexer.mll, interpreter/text/parser.mly, test/core/instance.wast
This PR extends the .wast script language such that definition and instantiation of a module can be separated. It makes the following extensions:
* Module declarations may be marked with the `definition` keyword, which suppresses automatic instantiation.
* A new command `(module instance <inst-name> <mod-name>)` allows explicit instantiation of such modules. 
* The assertions `assert_unlinkable` and `assert_trap` now accept an instance command as argument.
The previous forms of module declaration and assertions are still available, but now treated as a short-hand for a module definition followed by an instantiation or assertion.
For example:
```
(module definition $M ...)
(module instance $A $M)
(module instance $B $M)
(assert_trap (module instance $M) "message")
```
Module names and …
=> [interpreter] Implement new instance command

test/core/binary.wast, test/core/data.wast
It's a little more verbose than it needs to be due to originally being minified from a wabt exploit.
=> Test data count without data segment

.github/workflows/w3c-publish.yml
This will cause the default build of the W3C/echidna build pipeline (used on each
push) to use the  Candidate Recommendation Draft mode.
CR snapshots or any other document mode can still be selected when
running the workflow manually via the website, CLI or GH API.
=> Update W3C TR build from WD to CRD

.github/workflows/w3c-publish.yml
The w3c-status options correspond to the valid options for
Bikeshed's --md-status flag (i.e. Status metadata, https://speced.github.io/bikeshed/#metadata),
and refer to the W3C rec-track document
stages described in https://www.w3.org/policies/process/#maturity-stages
(Editor's Draft, Working Draft, Candidiate Recommendation Draft, and
Candidate Recommendation Snapshot).
=> Update document status input for W3C publishing to a choice value

test/js-api/wasm-module-builder.js
This was renamed to kWasmVoid in
https://github.com/WebAssembly/spec/commit/2f5a7c524fdc4dec280c6a53bc3cc800b6ad1c11.
=> wasm-module-builder: Fix left-over use of kWasmStmt

.github/workflows/w3c-publish.yml
This reverts commit 50429509db9a1cd0f71f8a8b93ded37e4720d4a9.
This will allow publishing more WD builds until the CR transition finishes.
=> Revert "Update W3C TR build from WD to CRD (#1797)"

document/web-api/index.bs
These considerations are aimed at answering the questions to consider from the TAG security and privacy questionnaire: https://www.w3.org/TR/security-privacy-questionnaire/
=> Add a minimal Security and Privacy Considerations section

test/core/call_indirect.wast
New test cases that found bugs in wizard, committing to upstream.
Links to fixes in wizard:
1. type mismatch: https://github.com/titzer/wizard-engine/commit/33b58749895dc5afdd2c032a31d1848475f04ce2
2. unknown type: https://github.com/titzer/wizard-engine/commit/4ad7eca1b98146fa4c8884b32c7e99c41f5d5a81
=> added tests for call indirect

.github/workflows/w3c-publish.yml, document/core/Makefile, document/js-api/Makefile, document/web-api/Makefile
This ensures that all 3 specs build and upload even if one fails. Also use 'uploaded' in the status text instead of 'published' to reflect possible dry run or validation failure.
=> [ci] Use build matrix to run W3C spec builds independently

document/core/util/bikeshed_fixup.py
Fix a sequence that Bikeshed is treating as a macro and rewriting.
This is a workaround for #1823
=> Escape latex newline commands with extra vertical space

document/js-api/index.bs
Adds explicit steps to run memtype and tabletype validation and throw a RangeError on failure. This explicitly satisfies the preconditions from the wasm embedding spec, and removes the need for the `initial <= maximum` check in the JS API spec.
One other small note: allocation failures on tables are now explicitly reported. This captures implementation limits on table length, which also weren't quite handled by the spec. (This removes a TODO referencing #584.)
Fixes #1792.
=> [js-api] Fix up missing preconditions on allocations

interpreter/script/js.ml
=> [interpreter] Fix JS module invocation

interpreter/script/js.ml
This reverts #1829 and implements a simpler & correcter fix.
=> [interpreter] Proper fix for JS conversion

test/js-api/wasm-module-builder.js
Rename the function import property from `type` to `type_index` to match the use site (l.1166):
```JS
if (imp.kind == kExternalFunction) {
section.emit_u32v(imp.type_index);
}
```
=> Fix wasm-module-builder.js

document/core/exec/modules.rst
I think these two members are missing here.
=> [spec] Add elem/data member to moduleinst in prose

.github/workflows/ci-interpreter.yml, .github/workflows/ci-spec.yml, interpreter/script/js.ml
This should fix WebAssembly/memory64#95.
=> [interpreter] Fix subtype condition for result patterns

test/build.py
=> build.py: generate JS/HTML wrappers for tests in subdirectories

document/core/appendix/embedding.rst
Looks like this was missing from 76bcf867.
=> embedding.rst: Fix heading underline. NFC

document/core/appendix/changes.rst, document/core/appendix/embedding.rst, document/core/binary/types.rst, document/core/exec/instructions.rst, document/core/syntax/types.rst, document/core/text/modules.rst, document/core/valid/instructions.rst, document/core/valid/matching.rst, interpreter/binary/decode.ml, interpreter/binary/encode.ml, interpreter/exec/eval.ml, interpreter/host/spectest.ml, interpreter/runtime/data.ml, interpreter/runtime/data.mli, interpreter/runtime/elem.mli, interpreter/runtime/memory.ml, interpreter/runtime/memory.mli, interpreter/runtime/table.ml, interpreter/runtime/table.mli, interpreter/runtime/value.ml, interpreter/syntax/free.ml, interpreter/syntax/operators.ml, interpreter/syntax/types.ml, interpreter/text/arrange.ml, interpreter/text/parser.mly, interpreter/valid/match.ml, interpreter/valid/valid.ml, test/core/memory.wast, test/core/memory64.wast, test/core/table.wast
In preparation for merging the proposal to the wasm-3.0 branch, this PR fixes various smaller issues I discovered when going through the diffs for the merge.
Spec:
- Removed unnecessary/mismatching lookup of table/memory type in execution prose
- Added missing result type lookup in formal rule for `table.size` and `memory.size`
- Fixed computation of -1 result value for `table.grow` and `table.size` to work for i64
- Some fixes around specification of text format for inline elements/data shorthand
- Fixed matching rules for tabletype/memtype to enforce same address type
- Added an entry for the proposal to the Appendix’ changelog
Interpreter:
- Fixed evaluation of v128 load/store instructions to work with i64
- Reworked bulk operation execution to still reduce to well-typed instructions …
=> Tweaks and fixes to Memory64 proposal

document/js-api/index.bs
ECMA-262 now uses these prose forms for type tests and has removed the old `Type` AO. See https://github.com/whatwg/html/pull/10635 for more info.
=> [js-api] Editorial: replace Type AO with new ECMA-262 type test convention

document/core/static/custom.css
At the moment mobile version of site looks broken. It seems that custom.css overrides alabaster.css, which had good mobile media query.
This minimal change makes spec readable on mobiles.
=> Fix mobile margin

test/core/gc/array.wast
Also test that the instructions trap when the offset and size overflow back to zero, with and without the segments having been dropped.
=> Test array.new_data and array.new_elem with dropped segments

document/js-api/index.bs, test/core/float_exprs.wast
Update them to refer to IEEE 754-2019. I've confirmed that the relevant section names and numbers in 754-2019 are the same.
=> Update references to IEEE 754-2008.

test/build.py
When converting tests to HTML for use in WPT, use the path to
the test harness in WPT's resources/ directory. This is also
important because the WPT test runner users this path inclusion
to discover the tests.
There are several more things I want to simplify here but I'm
starting with just this because it matches the sed transform
that @past originally wrote in
https://github.com/web-platform-tests/wpt/pull/49277
=> Use WPT version of test harness for HTML core test conversion

document/core/syntax/types.rst, document/core/valid/instructions.rst, document/core/valid/matching.rst, document/core/valid/types.rst
This PR changes the definition of `tagtype`, which was previously `functype`, into `deftype`,
and also modifies (hopefully) every use site of it, accordingly.
The issue arised from the fact that the `exn` proposal and the `gc` proposal were being developed independently,
and they were not merged properly.
=> Change the definition of `tagtype` from `functype` into `deftype`

document/core/util/bikeshed_fixup.py
This regex removes all the leading content up to the div containing the "Introduction" heading, but this content includes an opening `<section>` tag that wraps all of the front matter. The updated version of Bikeshed is throwing errors because of the unbalanced closing tag.
Fix this by adding the opening tag back.
=> Fix Bikeshed fixup to properly balance section elements

document/core/exec/numerics.rst
Corrected the explanation of `z1 >= z2` to accurately reflect its meaning.
=> [spec] Fixed incorrect description of fge operation

document/core/valid/instructions.rst
I noticed that the result type of store lane in the prose appears to be incorrect.
I have corrected this.
=> Fix wrong result type

document/core/valid/instructions.rst
I noticed that validation rule for `catch` and `catch_all` uses equality rather than subtype.
I have corrected it.
=> [spec] Fix validation rule for catch and catch all

document/core/valid/matching.rst
I noticed that subtype rule for exn appears to be missing.
I have added the rule.
=> [spec] Add missing subtype rule for exn

interpreter/valid/valid.ml, test/core/return_call_indirect.wast
This PR fixes a missing type check for `return_call_indirect` instruction.
`return_call_indirect` expects a function reference, and the module should be considered invalid if the non-function reference is given (as in `call_indirect` instruction).
However, the current validation behaves incorrectly, and pass such invalid module.
This PR fixes this error, and adds the new test case:
```wast
(assert_invalid
(module
(type (func))
(table 10 externref)
(func $return-call-indirect (return_call_indirect (type 0) (i32.const 0)))
)
"type mismatch"
)
```
=> [interpreter] Fix missing type check for `return_call_indirect`

document/core/exec/modules.rst
It seems that the arguments of allocmodule have not been updated.
I have corrected it.
=> [spec] Update allocmodule arguments

document/core/exec/instructions.rst, document/core/valid/instructions.rst
I noticed that validation rule for `array.new_default` uses an incorrect instruction name,
and there is also a minor typo in execution rule that a parenthesis is not in the subscript.
I have corrected it.
=> [spec] Fix array.new_default

test/core/align.wast
This PR adds tests for malformed binary-format memop flags to the wasm-3.0 tests.
The main-branch `align.wast` has malformed tests (added in https://github.com/WebAssembly/spec/pull/1751), but multi-memory liberalizes the encoding so the existing tests were changed to `assert_invalid` in multi-memory and wasm-3.0. This adds back some (more-extreme) examples of malformed flags.
=> [test] align.wast: add tests of malformed memop flags in wasm-3.0

document/core/text/types.rst
In memory64, the types of _limits_ `min` and `max` were updated to u64 in the abstract syntax and the binary format specification. This updates the text format spec to match.
This is already tested by the wasm-3.0 tests, e.g. this `assert_invalid` test from `memory.wast` is an `assert_malformed` on the main branch:
```wasm
(assert_invalid
(module (memory 0x1_0000_0000))
"memory size"
)
```
=> [spec] Update limits type in wasm-3.0 text format spec

document/core/text/instructions.rst, test/core/align.wast
In memory64/wasm-3.0,
- in the abstract syntax and binary format, the type of a memarg offset was updated to u64, and
- in the reference interpreter's text parser, the type of a memarg `align` $a = 2^n$ was updated to u64.
This updates the text format spec to match and adds tests for extreme cases. These surface some bugs/out-of-date parsing logic in WABT and wasm-tools.
=> [spec] Update align and offset type in text format for memory64

interpreter/valid/valid.ml, test/core/gc/extern.wast
Fix #1889.
@f52985, PTAL. Turns out we already have tests for the other const instructions, distributed over the respective test files.
=> [test/interpreter] Extern convert as const expr

test/harness/testharness.js
This was already done upstream in https://github.com/web-platform-tests/wpt/pull/50557.
=> Fix typo in testharness.js

test/core/simd/simd_select.wast
Hi!
I am proposing to add a select testcase for simd proposal 
I was one of the co-authors of simd implementation in WAMR and while our implementation was passing all the testsuite it didn't have support for v128 in select which was reported in https://github.com/bytecodealliance/wasm-micro-runtime/issues/4228
Hence adding the test to allow to catch failures like that earlier
=> Add select 128 testcase

interpreter/script/js.ml, test/core/gc/type-subtyping.wast
=> [interpreter] Support wrapping fancy function types in JS translation

document/core/appendix/changes.rst, document/core/valid/modules.rst
Triggered by WebAssembly/design#1539, this spells out the intended backwards-compatibility constraints we assume of future Wasm versions. I believe this captures what was discussed in that context.
=> [spec] Describe backwards-compatibility and reserve 0xFF opcode

test/core/binary.wast
Following up on #1900, this tests that 0xff is disallowed as an instruction and instruction prefix byte.
=> Test that 0xff is treated as an invalid opcode.

document/core/text/modules.rst
Pre-2018, the spec for the text format defined data and element segments as having an implicit "table 0" or "memory 0" with mathematical notation with an `𝑥′` that takes the value 0 if the memidx wasn't present in the text format.
https://github.com/WebAssembly/spec/pull/752 (responding to https://github.com/WebAssembly/reference-types/pull/3#discussion_r174529288) removed the definitions of `x'` and instead defined a text-format abbreviation for data and elem segments, e.g.:
> Also, the memory index can be omitted, defaulting to 0.
> ‘(’ ‘data’ ‘(’ ‘offset’ expr𝐼 ‘)’ . . . ‘)’ ≡ ‘(’ ‘data’ 0 ‘(’ ‘offset’ expr𝐼 ‘)’ . . . ‘)’
However, that commit only removed the prime symbol (from  `𝑥′` ) for the production for element segments but kept it in for data segments. This commit removes the …
=> [spec] Remove vestigial prime symbol in data segment text format

document/core/valid/matching.rst
Only one of the fieldtypes vector was superscripted with its arity in the definition of matching for composite types.
=> Added a missing exponent

document/core/valid/types.rst
Found a potential typo!
Before:
After:
=> [spec] Add missing 'addrtype' in memory type validation

document/core/util/mathjax2katex.py
Fixes #1924.
Bikeshed substitution steam-rolls over Latex content, which this script was supposed to fix up. But some of the cases either were outdated by changes to Sphinx/Katex/Bikeshed or never worked.
This patch now makes the script fail on warnings and adds suitable diagnostics, especially useful for CI. Unfortunately, I still can't get Bikeshed to run on my local machine.
=> [bikeshed] Fix Bikeshed patch-up script and add debugging aids

test/core/binary.wast, test/core/global.wast
This commit updates a few locations where tests assert that various bits are invalid to set for memories, tables, and globals:
* For memories bit 0b10 of the "flags" byte was tested to ensure that it's invalid, but this bit is used in the WebAssembly threads proposal to indicate a shared memory. Additionally bit 0b100 is used by the memory64 proposal and the 0b1000 bit is used by the custom-page-sizes proposal. This changes the test to assert that bit 0b10000 is invalid as it's not in use by any proposal.
* For tables bit 0b10 of the "flags" byte was tested to ensure that it's invalid, but this bit is used in the WebAssembly shared-everything-threads proposal to indicate a shared table. Additionally bit 0b100 is used by the memory64 proposal. This changes the test to assert that bit …
=> Update bits used for malformed memory/table/global flags

document/core/valid/instructions.rst, interpreter/valid/valid.ml, test/core/br_on_non_null.wast
=> [interpreter/spec] Consistent nullability for br_on_non_null

document/core/binary/conventions.rst, document/core/binary/instructions.rst, document/core/text/conventions.rst, document/core/text/instructions.rst, test/core/binary.wast, test/core/global.wast
This is intended to pull in a few extra commits that are otherwise causing conflicts to assist with updating the [testsuite repository](https://github.com/WebAssembly/testsuite) with the latest version of all tests.
=> Merge `main` into `wasm-3.0`

document/core/appendix/algorithm.rst
Field `height` had apparently been renamed at some point between 2.0 and 3.0. There were some lines where the old name remained.
=> Fix field name inconsistency

test/core/simd/simd_i32x4_dot_i16x8.wast
Previously, input lanes were all identical, which hid bugs in implements, such as https://github.com/titzer/wizard-engine/pull/443
=> [simd] Add additional test input for i32x4.dot_i16x8_s

spectec/src/al/ast.ml, spectec/src/backend-prose/print.ml, spectec/src/backend-prose/render.ml, spectec/test-prose/TEST.md
*not* the first non-value entry of the stack is a label →
the first non-value entry of the stack is *not* a label
=> Fix prose rendering of NotOp ContextKindE

document/core/syntax/instructions.rst
Fix typos in section "Structure > Instructions > Memory Instructions".
=> [spec] Fix typos
