- ml-proto/README.md
Easy OCaml install with Homebrew
> [XS] Add OSX install instructions

- ml-proto/TestingTodo.md
Following up on Luke's suggestion in #25, here's the testing TODO list in markdown format so that it can be edited collaboratively.
> Create an initial testing TODO list.

- ml-proto/travis/build-test.sh
@flagxor, also invoking make shouldn't be necessary.
> Simplify build-test

- ml-proto/README.md
This is the command used by the travis build and the runtests.py script.
> Update the README.md to use the up to date build command.

- ml-proto/src/Makefile
- ml-proto/src/given/float32.ml
- ml-proto/src/given/float32.mli
- ml-proto/src/given/float64.ml
- ml-proto/src/given/float64.mli
- ml-proto/src/host/parser.mly
- ml-proto/src/spec/arithmetic.ml
- ml-proto/src/spec/memory.ml
- ml-proto/src/spec/types.ml
- ml-proto/src/spec/values.ml
This PR is not yet ready for merging!
This is some exploratory code implementing wasm-compatible float64 arithmetic in OCaml. This is my first ML code and I'm still learning, so please don't be gentle. Also, it doesn't compile yet because I haven't figured out how to use int64 yet. And, it doesn't have tests yet. And nothing is using it yet. And it may be buggy. I'm interested in any and all feedback about the approach, how best to structure the code, coding style, or anything.
I expect to eventually refactor this code to support float32 as well.
> wasm-compatible float32 and float64 arithmetic

- ml-proto/Makefile
This just makes some minor Makefile tweaks to make the Makefile a little friendlier.
> Makefile tweaks

- ml-proto/host/lexer.mll
- ml-proto/host/parser.mly
- ml-proto/spec/ast.ml
- ml-proto/spec/check.ml
- ml-proto/spec/eval.ml
- ml-proto/spec/sugar.ml
- ml-proto/spec/sugar.mli
- ml-proto/test/select.wast
Select is a conditional operator which evaluates a condition and 2 input
operands, and returns the first if the condition is nonzero, and the
second otherwise.
> Support select operator

- ml-proto/host/lexer.mll
- ml-proto/host/parser.mly
- ml-proto/spec/ast.ml
- ml-proto/spec/check.ml
- ml-proto/spec/eval.ml
- ml-proto/spec/sugar.ml
- ml-proto/spec/sugar.mli
- ml-proto/test/select.wast
- ml-proto/test/unreachable.wast
Add an expression which typechecks in any context, and always traps when
executed.
> Add unconditional unreachable expression

- ml-proto/host/parser.mly
- ml-proto/spec/ast.ml
- ml-proto/spec/desugar.ml
- ml-proto/test/labels.wast
Matching up with v8-prototype and https://github.com/WebAssembly/design/pull/464 .
Also, add simple test for br_if.
> Allow optional argument to br_if

- ml-proto/spec/desugar.ml
- ml-proto/test/labels.wast
> Make br_if strict in 2nd operand

- ml-proto/README.md
Not quite sure what the `<switch>` non-terminal is for, but it looks wrong.
> Fix tableswitch syntax.

- ml-proto/test/labels.wast
- ml-proto/test/unreachable.wast
https://github.com/WebAssembly/binaryen/issues/161
https://github.com/WebAssembly/binaryen/issues/160
> Add some tests failing wasm-as.

- ml-proto/spec/desugar.ml
- ml-proto/test/switch.wast
- ml-proto/winmake.bat
> Fix bug in tableswitch desugaring

- ml-proto/test/block_comments.wast
https://github.com/WebAssembly/spec/pull/232
> Add tests for block comments, in a separate file.

- ml-proto/README.md
Addressing #64, among other things.
> Clarify lexical syntax of names and strings

- ml-proto/Makefile
- ml-proto/README.md
> Don't build winmake.bat with `all` target

- ml-proto/README.md
Also, use * rather than `<i>` for italics.
> Use relative links in README.md

- interpreter/README.md
- interpreter/host/main.ml
- interpreter/spec/ast.ml
- interpreter/spec/decode.ml
- interpreter/spec/encode.ml
- interpreter/spec/eval.ml
- interpreter/spec/valid.ml
- interpreter/test/binary.wast
- interpreter/text/arrange.ml
- interpreter/text/parser.mly
> Release binary 0xD

- interpreter/spec/encode.ml
...which would go totally wrong for "negative" numbers.
> Fix vu32 encoding

- interpreter/host/js.ml
> Fix NaN fix

- interpreter/README.md
- interpreter/test/block-end-label-mismatch.fail.wast
- interpreter/test/block-end-label-superfluous.fail.wast
- interpreter/test/if-else-end-label-mismatch.fail.wast
- interpreter/test/if-else-end-label-superfluous.fail.wast
- interpreter/test/if-else-label-mismatch.fail.wast
- interpreter/test/if-else-label-superfluous.fail.wast
- interpreter/test/if-end-label-mismatch.fail.wast
- interpreter/test/if-end-label-superfluous.fail.wast
- interpreter/test/loop-end-label-mismatch.fail.wast
- interpreter/test/loop-end-label-superfluous.fail.wast
- interpreter/test/stack.wast
- interpreter/text/parser.mly
> Allow reference to block label on END and ELSE

- interpreter/README.md
> Fix broken link to AstSemantics (another one)

- interpreter/spec/eval.ml
> Consistently check import types during instantiation

- interpreter/test/custom_section.wast
> added custom section tests

- interpreter/test/memory.wast
To address omissions mentioned in WebAssembly/design#889.
> Add tests for multiple or missing memories

- interpreter/test/custom_section.wast
This adds some custom section tests that test custom sections in between other arbitrary sections.
> a few more custom section tests

- interpreter/test/start.wast
> Add test for start function being an import

- interpreter/test/call_indirect.wast
related https://github.com/WebAssembly/spec/issues/404
> added test with invalid table indices

- interpreter/host/js.ml
More async compat addressing #410: JS translation now wraps toplevel actions (with no assertion) into `run` function:
```
(invoke "f")
(get "x")
```
becomes
```
run(() => call($$, "f"))
run(() => get($$, "x"))
```
Also, no longer mutate `$$` variable, but assign fresh vars.
Moreover, output original line numbers as comments for easier reference.
(Plus some minor code clean-up.)
> Add run function to JS harness

- test/core/unreached-invalid.wast
This PR adds an interesting case that combines unreachable, select, and if.
> Add test for interesting unreachable + select + if combination

- document/Makefile
- document/concepts/index.rst
- document/concepts/overview.rst
- document/deploy.sh
- document/introduction/index.rst
- Add short section on scope of this spec
- Add section introducing the main Wasm concepts
- Incorporate script automating push to gh-pages
For test rendering, see http://webassembly.github.io/spec/
> Scope & concept overview

- test/core/binary.wast
- test/core/custom_section.wast
This adds a few miscellaneous binary-format tests.
> Some binary tests

- test/core/float_exprs.wast
- test/core/float_misc.wast
This PR contains a handful of floating-point tests that previously were bundled into https://github.com/WebAssembly/spec/pull/470, but which I've now pulled out to make them easier to review.
> Float tests

- test/build.py
#453 is a case of bad UX: a developer would expect that `build.py` just generates the tests. What's hidden in there is that the test generator uses the wasm spec interpreter, so it needs to be up to date and compiled in the first place.
This PR makes that we recompile the spec interpreter before generating the tests, unless explicitly told not to (with `--dont-recompile`).
@rossberg-chromium, can you have a look, please?
> Automatically recompile the spec interpreter before generating the tests

- test/harness/index.js
assert_invalid uses module() and checks:
assert_true(e instanceof WebAssembly.CompileError, "expected invalid failure:");
But module() catches and re-throws a plain Error, so instanceof cannot succeed.
While I'm here, improve the error messages a bit.
> Test harness: fix assert_invalid, improve error messages

- test/core/traps.wast
Add test for dead-code with i32.div_s & i64.div_s (min_int, -1)
> Add test in traps.wast

- document/custom.css
Tweak logo size, font size, and other metrics.
> [spec] Various CSS tweaks

- document/core/appendix/algorithm.rst
- document/core/conf.py
- document/core/util/pseudo-lexer.py
- document/core/valid/conventions.rst
Preview: http://webassembly.github.io/spec/appendix/algorithm.html
> [spec] Explain validation algorithm

- document/core/appendix/custom.rst
- document/core/appendix/index.rst
- document/core/appendix/names.rst
- document/core/util/math.def
Preview: http://webassembly.github.io/spec/appendix/custom.html
> [spec] Specify name section

- document/core/util/mathdef.py
> [spec] Fix underscores in HTML hrefs

- test/core/unreached-invalid.wast
See https://github.com/WebAssembly/wabt/issues/586.
> Add test for unreachable tee_local value

- test/core/unreached-invalid.wast
See https://github.com/WebAssembly/wabt/pull/589.
> Add test for unreachable br_if value

- document/core/intro/introduction.rst
- document/core/intro/overview.rst
- document/core/syntax/values.rst
This PR fixes some small issues I noticed when reading through the spec. Please take a special look at the changes to the floating point parts.
> Fix small issues in the spec document

- test/core/call_indirect.wast
- test/core/elem.wast
- test/core/elements.wast
Some of the tests were moved from call_indirect.wast.
> Add tests for the element section

- document/core/syntax/values.rst
This PR adds a note which describes the value range of subnormal floating point numbers.
> Explain the subnormal exponent

- document/core/exec/instructions.rst
> [spec] Specify name mapping for cvtop

- interpreter/valid/valid.ml
- test/core/unreached-invalid.wast
Adds a few tests and fixes a bug in interpreter error message.
See https://bugs.chromium.org/p/v8/issues/detail?id=6651
> [test] Add tests for unreachable br_if

- document/core/binary/instructions.rst
> Include reserved byte in call_indirect encoding

- document/core/exec/instructions.rst
> [spec] Add note re set_global

- document/core/intro/introduction.rst
> [spec] Add note regarding authorative role of standard dependencies

- document/core/appendix/embedding.rst
> [spec] Support reading and writing empty table entries

- document/core/syntax/instructions.rst
> [spec] Add note on log2 representation for alignment

- document/core/appendix/properties.rst
- document/core/exec/modules.rst
Address #603. Also, tweak the wording of the soundness theorem.
> [spec] Fix variable names in instantiation

- document/core/exec/modules.rst
> typo in modules.html

- document/core/valid/instructions.rst
> [spec] Fix validation of `call_indirect`

- document/js-api/index.bs
See commit messages for details
cc @rossberg @lukewagner
> Some editorial improvements to the Wasm/JS spec

- interpreter/README.md
- test/harness/index.js
> [interpreter] Remove remnants of assert_soft_invalid

- test/core/labels.wast
This test helped me diagnose https://github.com/WebAssembly/spec/issues/608
Maybe it is a good idea to include the test like this one? 
Feel free to close
> Test the difference between label and result types in a loop

- document/travis-deploy.sh
Submitting TBR. Getting the travis build green again.
> Fixing when cleanup happens in travis build.

- document/core/Makefile
> [spec] Adjust sed hack for setting MAthJax buffer size

- document/js-api/index.bs
- Remove irrelevant issues and notes
- Clean up wording to indicate more clearly what it is for
> [spec] Editorial: Simplify introduction

- test/core/binary.wast
Resolves #700 
Just testing the grounds. Am I going in the right direction @rossberg  ?
> Add testing for reserved bytes

- document/core/exec/numerics.rst
> [spec] Fix typo in fdiv

- document/js-api/index.bs
> [spec] Normative: Detach previous JS ArrayBuffer from grow_memory

- document/core/exec/numerics.rst
> [spec] Fix irem_s

- interpreter/binary/decode.ml
Fixes crash noted [here](https://github.com/WebAssembly/wabt/issues/760#issuecomment-376764583).
> [interpreter] Fix len32 check to unsigned

- document/core/Makefile
- document/core/index.bs
- document/core/util/bikeshed/conf.py
- document/core/util/bikeshed_fixup.py
- document/core/util/mathdefbs.py
- document/core/util/mathjax2katex.py
Limiting TOC depth.
https://github.com/WebAssembly/spec/issues/675
Bringing back hyperlinks.
https://github.com/WebAssembly/spec/issues/667
Fix missing spaces.
https://github.com/WebAssembly/spec/issues/669
Working around katex bug with multi-line + hrefs.
> Fixing up formatting for bikeshed.

- document/core/util/katex_fix.patch
Also centering:
https://github.com/WebAssembly/spec/issues/668
> Fixing display math formatting.

- document/core/util/bikeshed_fixup.py
https://github.com/WebAssembly/spec/issues/679
> Don't number the Appendix.

- document/core/appendix/index.rst
- document/core/util/bikeshed_fixup.py
Fixes:
https://github.com/WebAssembly/spec/issues/677
> Adding index of instructions for bikeshed.

- document/core/util/mathjax2katex.py
Sadly hacky.
Fixes:
https://github.com/WebAssembly/spec/issues/669
> Working around bad kerning.

- document/core/util/katex_fix.patch
This makes us pass the W3C CSS validator again.
> [editorial] Remove !important from css selector.

- document/core/util/mathjax2katex.py
Fixes parts of:
https://github.com/WebAssembly/spec/issues/669
> [editorial] Switch to using display mode.

- document/core/Makefile
- document/core/util/bikeshed_fixup.py
- document/core/util/katex_fix.patch
- document/core/util/mathjax2katex.py
Re-fix gray bars.
Fix formatting + coloring of code.
Fix math fragments inside span (period / comma not tight).
> [editorial] Fix multiple formatting issues.

- document/core/exec/runtime.rst
- document/core/syntax/conventions.rst
- document/core/syntax/instructions.rst
- document/core/syntax/modules.rst
- document/core/syntax/values.rst
See @dschuff's comments in #726.
> [spec] Address review comments for Section 2

- document/core/appendix/properties.rst
- document/core/exec/instructions.rst
Address #723 and also #781.
@conrad-watt, note the change to the definition of valid host function. Will your proof still go through with the modified definition?
> [spec] Address review by eholk

- document/core/text/conventions.rst
- document/core/text/lexical.rst
- document/core/text/modules.rst
- document/core/text/values.rst
> [spec] Address comments by sbc100

- document/web-api/index.bs
> [web-api] Changes from review

- document/core/appendix/index-types.rst
> [spec] Fix result type brackets in index

- document/core/valid/modules.rst
> [spec] Editorial: Fix minor typo in module instantiation

- test/core/align.wast
- test/core/memory.wast
- Fulfill the test coverage of Alignment section
- Centralize alignment relative tests in one file
@rossberg, could you PTAL? Thanks!
> [test] Add tests for Alignment

- test/core/float_exprs.wast
- test/core/float_literals.wast
- test/core/float_misc.wast
- test/core/names.wast
This adds a handful of miscellaneous floating-point and Unicode tests.
> Miscellanous floating-point and unicode tests

- document/index.html
Make links more explicit and equal.
> [spec] Reorganise main links

- document/core/util/mathjax2katex.py
* There was an extra `</span>` in the math fragments; this occurred when
replacing the output before "katex-html". This removes the extra
closing tag, and also adds a function to catch look for balanced tags
in the math output. It's not very clever, but it works for the current
math fragments.
* Some `<a>` tags were being generated with multiple "style" attributes,
to prevent underlining links.
The fix here is to add a new style section instead of annotating each
element.
> Some html validation fixes for bikeshed spec

- document/core/appendix/index-rules.rst
- document/core/exec/modules.rst
- document/core/valid/types.rst
- interpreter/valid/valid.ml
- test/core/memory_grow.wast
Address #861. Also tweak interpreter to match new rule structure.
> [spec] Add missing range checks on memory limits

- document/core/Makefile
- document/js-api/Makefile
- document/web-api/Makefile
* `make WD-tar`: Generate the Working Draft tar file to submit
* `make WD-echidna`: Publish the Working Draft via Echidna
> Add commands to generate Working Draft

- .travis.yml
See https://github.com/sphinx-doc/sphinx/issues/5417
> Pin sphinx to v1.7.9 to workaround upstream bug

- document/js-api/index.bs
> [js-api] Verify initial < maximum in Memory ctor

- test/core/select.wast
- Test select as the argument of control constructs/instructions
- Test select with invaild operands
> [test] Improve test coverage of select.wast

- document/js-api/index.bs
> [js-api] Add definition of Memory#buffer getter

- document/js-api/index.bs
Fixes https://github.com/WebAssembly/spec/issues/838
> [jsapi] remove optional params (TableDescriptor/MemoryDescriptor)

- test/js-api/memory/constructor.any.js
Was probably copied from `WebAssembly.Table` tests.
> tests: remove invalid property

- test/core/local_get.wast
- test/core/local_set.wast
- Fixed bugs in few tests that test `local.get` rather `local.set` in local_set.wast
- Compared two test files and supplement the missing checkponits
> [test] Made tests in local_get/set.wast consistent

- interpreter/README.md
According to https://github.com/WebAssembly/spec/issues/884#issuecomment-426433329
> Update text format operators

- test/core/globals.wast
- test/core/load.wast
- test/core/local_get.wast
- test/core/local_set.wast
- test/core/local_tee.wast
- test/core/store.wast
This is the first part to fix following task in typecheck.wast:
;; TODO(stack): more of the above
Split this task into sevaral PRs is for the purpose of easier reviewing.
> [test] Add more tests for operand missing -Part1

- test/core/run.py
> [test] Nicer error message for missing executable.

- test/core/imports.wast
> [test] Use registered module name in imports.wast

- document/core/exec/numerics.rst
> [spec] Fix definition of littleendian

- test/core/block.wast
- test/core/br_if.wast
- test/core/br_table.wast
- test/core/call.wast
- test/core/call_indirect.wast
- test/core/loop.wast
- test/core/memory_grow.wast
- test/core/select.wast
This is the last part to fix following task in typecheck.wast
;; TODO(stack): more of the above
> [test] Add more tests for operand missing -Part3

- test/js-api/limits.any.js
> [jsapi] Fix typo in limits.any.js

- document/core/appendix/index-instructions.rst
> Fix `if` instruction type in index

- document/core/binary/modules.rst
As suggested [by @binji](https://github.com/WebAssembly/spec/issues/990#issuecomment-483323773).
> [spec] Add paragraph break for more emphasis

- document/core/appendix/implementation.rst
Updates `.rst` file instead of `.html` (#1009)
> Very small typo

- document/core/appendix/custom.rst
> [spec] Constrain name section ordering

- test/core/binary.wast
tweak some tests order a bit to make it looks beauty passingly.
> [test] Add more tests for unsigned LEB128 with non-minimal length

- document/core/util/bikeshed_fixup.py
This will automatically add these entries to the normative references
section which is auto-generated at the bottom of the document.
> [spec] Replace URLs with bikeshed biblio refs

- document/core/syntax/instructions.rst
> [spec] Tweak wording

- document/core/conf.py
- document/core/exec/instructions.rst
- document/core/exec/modules.rst
- document/core/exec/numerics.rst
- document/core/exec/runtime.rst
- document/core/index.rst
- document/core/syntax/modules.rst
- document/core/util/macros.def
Addresses lost feedback from #728. Also, adds a bit of frontmatter to multi-page version to match relevant information from the W3C version.
> [spec] Address feedback on section 4

- interpreter/exec/f32.ml
- interpreter/exec/f32_convert.ml
- interpreter/exec/f64.ml
- interpreter/exec/f64_convert.ml
- interpreter/exec/float.ml
- interpreter/exec/i64_convert.ml
- interpreter/exec/int.ml
- test/core/conversions.wast
> [interpreter] Fix edge cases for f32_convert_i64

- interpreter/README.md
> Add `assert_exhaustion` to README

- document/js-api/index.bs
This at least gets somewhat close to defining what's actually intended.
Fixes #810.
> Rewrite definition of error types.

- document/js-api/index.bs
- document/web-api/index.bs
I will be taking over Dan's duties as editor.
> Editorial: Update editor information in JS/Web API specifications.

- document/core/appendix/properties.rst
Background: see https://github.com/WebAssembly/multi-value/issues/29
This is the (1): the minimal and  straightforward fix
> [spec] fix valid tableinst and meminst premises

- document/core/binary/modules.rst
> [spec] Clarify note on custom sections

- document/js-api/index.bs
> [js-api] Remove redundant [[Values]] slot for Tables.

- document/js-api/index.bs
> [js-api] Generalize the note about imports validation.

- document/core/exec/instructions.rst
> [spec] Fix negative value nit

- document/web-api/index.bs
> [web-api] Fix the link to the CompileError definition.

- .travis.yml
Also use the apt addon [0] to install our dependencies.
[0] https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-with-the-apt-addon
> Upgrade travis environment to Bionic

- .travis.yml
> Upgrade to latest Sphinx release (2.4.4)

- test/harness/async_index.js
- test/harness/sync_index.js
This commit updates the harness/index.js files to support the
multi-value proposal.
> Update harness/index.js for multi-value

- document/core/util/mathjax2katex.py
Also reduce the threading from 40 to something based on system's
available CPU (see
https://docs.python.org/3/library/os.html#os.cpu_count for explanation
of using this). This makes the build a bit more manageable on systems
without as many cores.
Fixed #1207.
> Make KaTeX errors fail the build

- document/README.md
> Add some more instructions on how to build the spec

- document/js-api/index.bs
Fixes https://github.com/WebAssembly/spec/issues/1184.
> Specify the entry and incumbent realm for host functions.

- interpreter/.merlin
This is useful to specify our soruce/build structure to Meriln to enable
IDE like features (syntax check in editor, go to definition, etc.)
See https://github.com/ocaml/merlin.
> Add merlin config file

- document/web-api/index.bs
syncs Web API media type registration with proposed text in #573
> ~ modernize media type registration

- interpreter/Makefile
Add a `partest` target to the interpreter makefile that runs all tests but as separate targets, so that it can benefit from `make -j`. That is, `make -j partest` runs the test suite in parallel processes.
> [test] Parallel test run target

- document/core/exec/numerics.rst
> Fix signed convert subscript

- document/web-api/index.bs
> [web-api] Update media-type registration for review.

- test/core/global.wast
Split out from https://github.com/WebAssembly/extended-const/pull/2
> Add testing for globals initialized by othert (imported) globals

- document/core/text/modules.rst
> [spec] Fix side condition about fresh ids

- document/web-api/index.bs
Same as #1325. Sorry for missing this in the first PR.
> Fix the Editor metadata format

- document/core/syntax/modules.rst
Just fixing a tiny grammar mistake I noticed while reading the spec.
> Tiny Grammar Fix

- document/js-api/index.bs
See <https://github.com/tc39/ecma262/pull/2116>.
> [js-api] Update CreateBuiltinFunction call for ES changes.

- document/core/intro/overview.rst
found this while introducing someone to the wasm spec 😄
> remove outdated footnote

- document/core/intro/overview.rst
> [spec] Add reference types to overview

- proposals/README.md
> Add a link to the proposals repo

- document/core/text/types.rst
> [spec] Add note regarding parameter names

- document/core/binary/types.rst
> [spec] Fix missing mention of vectype

- interpreter/Makefile
> [interpreter] Fix warning flags for OCaml 4.13

- document/core/syntax/modules.rst
> [spec] Remove obsolete note

- interpreter/README.md
It previously stated that the formal spec did not exist, but the spec has existed for years now.
> Update interpreter README

- document/core/exec/instructions.rst
Left-over from before references.
> [spec] Remove an obsolete exec step

- document/core/syntax/instructions.rst
> [spec] Fix abstract grammar for const immediate

- document/core/text/modules.rst
> [spec] Fix context composition in text format

- test/core/linking.wast
- test/core/simd/simd_linking.wast
> [test] Move SIMD linking test to simd dir

- document/core/exec/instructions.rst
> [spec] Fix reduction rule for label

- document/core/syntax/values.rst
> [spec] Clarifying note about canonical NaNs

- document/core/util/bikeshed_fixup.py
> [bikeshed] Work around bikeshed troubles

- document/core/exec/instructions.rst
This pull request refactors the prose-form specification for execution of instructions.
It is mainly refactored to be more consistent in style, and some minor issues are fixed.
> [spec] Refactor the prose-form specification

- document/core/binary/modules.rst
> [spec] Add note about sction order

- document/core/appendix/properties.rst
@raoxiaojia, please take a look again.
> [spec] Fix refs field in context in appendix

- document/js-api/index.bs
> [js-api] Editorial: fix some bikeshed warnings

- document/js-api/index.bs
- document/util/htmldiff.pl
- proposals/bulk-memory-operations/Overview.md
- proposals/multi-value/Overview.md
- proposals/reference-types/Overview.md
- proposals/simd/SIMD.md
- test/core/float_exprs.wast
- test/core/simd/simd_load.wast
- test/core/simd/simd_store.wast
- test/core/utf8-custom-section-id.wast
- test/core/utf8-import-field.wast
- test/core/utf8-import-module.wast
This does not fix the following issue:
```
No 'dfn' refs found for 'object address'.
```
> [js-api] Fix bikeshed errors

- document/core/index.bs
This is necessary for Bikeshed to generate CRs
> Add Implementation Report metadata

- document/js-api/index.bs
- document/web-api/index.bs
> Add Implementation Report fields to metadata for JS and Web API specs

- .github/workflows/ci-spec.yml
> [ci] Bump upload/download-artifact to v4

- document/web-api/index.bs
The registration has been completed.
> Update IANA media type registration section in Web API

- .github/workflows/ci-interpreter.yml
- .github/workflows/ci-spec.yml
- .github/workflows/w3c-publish.yml
This should fix various deprecation warnings we are getting in CI.
> [ci] Update CI action versions

- document/core/valid/instructions.rst
> [spec] Fix typo in type for store_lane

- document/core/binary/modules.rst
Address long-standing [comment](https://github.com/WebAssembly/design/issues/1513#issuecomment-2026154201) on WebAssembly/design#1513.
> [spec] Change misleading wording in note

- document/core/valid/matching.rst
> [spec] Fix typos

- document/core/valid/modules.rst
> [spec] Fix missing address type in segment typing

- test/core/bulk.wast
- test/core/data.wast
This PR adds additional test cases for the textual syntax of passive data segments (especially for testing the empty data).
> [test] Add test for passive data syntax

- test/core/type-rec.wast
> [test] Add syntax and scoping tests for type rec
